### ISSUE TITLE
No option to specify separate database for usage and authentication

### ISSUE THREAD

**Issue by stepacool** [mongo-express/mongo-express#1077]
Hello! Using this in a docker environment. Need to use it without admin privilleges with the same user that my backend uses. The issue is, the user is authorized against one database, but used and has read/write privilleges in another.

Mongo-express doesn't have the option to separately specify AUTH_DATABASE and just DATABASE.
When I specify ME_CONFIG_MONGODB_AUTH_DATABASE, it automatically tries to  listCollections on the same database which I think is strange. My backend's Pymongo has an option to specify MONGODB_DATABASE and MONGODB_AUTH_SOURCE.

I think it'd be a great idea to allow the user to specify a database for usage while authenticating against a different auth database.

Full output:
`
(node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:7) UnhandledPromiseRejectionWarning: MongoError: not authorized on admin to execute command { listCollections: 1, filter: {}, cursor: {}, nameOnly: false, lsid: { id: UUID("89cce0b0-0c2f-441a-bb8b-d5cf5b9bb57e") }, $db: "admin" }
    at Connection.<anonymous> (/node_modules/mongodb/lib/core/connection/pool.js:453:61)
    at Connection.emit (events.js:314:20)
    at processMessage (/node_modules/mongodb/lib/core/connection/connection.js:456:10)
    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connection.js:625:15)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by stepacool** [comment]
Just in case - I can manage it work with
**ME_CONFIG_MONGODB_URL** by specifying the database to work in the path and the auth database via a query parameter **authSource**. But it'd still be nice to have the functionality like that without the URI strings.
