### ISSUE TITLE
Cannot open collections on MongoDB Version 4.2.22

### ISSUE THREAD

**Issue by dariowrk** [mongo-express/mongo-express#1082]
With the current GitHub Master build connected to a MongoDB with version 4.2.22 i get the following error when trying to open a collection:

**GUI Error:**
sub-pipeline in $facet stage cannot be empty

**LOG Error:**
MongoServerError: sub-pipeline in $facet stage cannot be empty
    at Connection.onMessage (/mongo-express/node_modules/mongodb/lib/cmap/connection.js:227:30)
    at MessageStream.<anonymous> (/mongo-express/node_modules/mongodb/lib/cmap/connection.js:60:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/mongo-express/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
    at MessageStream._write (/mongo-express/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at TLSSocket.ondata (node:internal/streams/readable:766:22)
    at TLSSocket.emit (node:events:513:28) {
  operationTime: new Timestamp({ t: 1671624857, i: 1 }),
  ok: 0,
  code: 2,
  codeName: 'BadValue',
  '$clusterTime': {
    clusterTime: new Timestamp({ t: 1671624857, i: 1 }),
    signature: {
      hash: new Binary(Buffer.from("d9937b084917caaf1e0bcb0cc594c5941fd2af4d", "hex"), 0),
      keyId: new Long("7128446049684815889")
    }
  },
  [Symbol(errorLabels)]: Set(0) {}
}

It seems to work fine on MongoDB version 5.

**Comment by dariowrk** [comment]
Have fixed this temporarily by editing $facet building in collection.js:

  exp._getQueryAggregate = function (req, query, queryOptions) {
    return [
      {
        $facet: {
          data: [
            // Array.isArray(query) checks if query is [] and exclude { ... } (bad/empty query)
            ...(req.query.runAggregate === 'on' && Array.isArray(query))
              ? query
              : ((Object.keys(query).length > 0)
                ? [{ $match: query }]
                **: [{ $match: {} }]),**
            ...(Object.keys(queryOptions.sort).length > 0) ? [{
              $sort: queryOptions.sort,
            }] : [],
            ...(Object.keys(queryOptions.projection).length > 0) ? [{
              $project: queryOptions.projection,
            }] : [],
          ],
        },
      },
      {
        $project: {
          'metadata.total': { $size: '$data' },
          data: { $slice: ['$data', queryOptions.skip, queryOptions.limit] },
        },
      },
    ];
  };
