### ISSUE TITLE
Unable to read document with integer id

### ISSUE THREAD

**Issue by rtritto** [mongo-express/mongo-express#1177]
### Steps to reproduce
- Create a document having an integer as _id (e.g. `{ _id: 1, ... }` )
- Call `GET /db/<DB_NAME>/<COLLECTION_NAME>/<_id>`
- Output:
```console
[0] C:\<PATH>\mongo-express\node_modules\bson\lib\error.js:41
[0]         var _this = _super.call(this, message) || this;
[0]                            ^
[0]
[0] BSONTypeError: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
[0]     at new BSONTypeError (C:\<PATH>\mongo-express\node_modules\bson\lib\error.js:41:28)
[0]     at new ObjectId.createFromHexString (C:\<PATH>\mongo-express\node_modules\bson\lib\objectid.js:238:19)
[0]     at buildId (file:///C:/<PATH>/mongo-express/lib/router.js:41:12)
[0]     at file:///C:/<PATH>/mongo-express/lib/router.js:184:17
[0]     at paramCallback (C:\<PATH>\mongo-express\node_modules\express\lib\router\index.js:415:7)
[0]     at param (C:\<PATH>\mongo-express\node_modules\express\lib\router\index.js:395:5)
[0]     at paramCallback (C:\<PATH>\mongo-express\node_modules\express\lib\router\index.js:412:21)
[0]     at file:///C:/<PATH>/mongo-express/lib/router.js:173:5
[0]     at paramCallback (C:\<PATH>\mongo-express\node_modules\express\lib\router\index.js:415:7)
[0]     at param (C:\<PATH>\mongo-express\node_modules\express\lib\router\index.js:395:5)
```

**Comment by ch1seL** [comment]
Was this fix included in the latest release of the Docker image? I'm getting this error right now on the latest revision.

**Comment by DesktopMan** [comment]
> Was this fix included in the latest release of the Docker image? I'm getting this error right now on the latest revision.

I'm also having this issue on the latest Docker image, so it seems like the fix is not included.
