### ISSUE TITLE
ME_CONFIG_MONGODB_ENABLE_ADMIN seems default to true instead of false

### ISSUE THREAD

**Issue by fkarakas** [mongo-express/mongo-express#1308]
Hello,
Using latest version of the docker image, just to let you know that the variable seems to be true by default, i put false and avoid the following error:
```
  ME_CONFIG_MONGODB_URL: "mongodb://xxxx"
  ME_CONFIG_BASICAUTH_USERNAME: ""
  ME_CONFIG_OPTIONS_EDITORTHEME: "ambiance"
  ME_CONFIG_OPTIONS_READONLY: "true"
  ME_CONFIG_MONGODB_ENABLE_ADMIN: "false" # Add this variable to avoid not authorized on admin error
```
```
MongoServerError: not authorized on admin to execute command { serverStatus: 1, lsid: { id: UUID("21872e7b-8acb-4ae1-a10d-a161b62e441a") }, $clusterTime: { clusterTime: Timestamp(1696857308, 1), signature: { hash: BinData(0, 24BE3220BC71DFEA1DA8069EB7FD1DF1FBF32DAA), keyId: 7249349263103098881 } }, $db: "admin" }
    at Connection.onMessage (/node_modules/mongodb/lib/cmap/connection.js:231:30)
    at MessageStream.<anonymous> (/node_modules/mongodb/lib/cmap/connection.js:61:60)
    at MessageStream.emit (node:events:517:28)
    at processIncomingData (/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
    at MessageStream._write (/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at Socket.ondata (node:internal/streams/readable:777:22)
    at Socket.emit (node:events:517:28) {
  operationTime: new Timestamp({ t: 1696857308, i: 1 }),
  ok: 0,
  code: 13,
  codeName: 'Unauthorized',
  '$clusterTime': {
    clusterTime: new Timestamp({ t: 1696857308, i: 1 }),
    signature: {
      hash: new Binary(Buffer.from("24be3220bc71dfea1da8069eb7fd1df1fbf32daa", "hex"), 0),
      keyId: new Long("7249349263103098881")
    }
  },
  [Symbol(errorLabels)]: Set(0) {}
}
```

**Comment by ironoa** [comment]
same issue with image version `1.0.2-20` and mongo `7.0.5`

I had to set `ME_CONFIG_MONGODB_ENABLE_ADMIN` to false to get rid of the `not authorized on admin to execute command` error

**Comment by dmvdven** [comment]
Thank you for mentioning this.

This saved me probably a lot more hours of research. Had the exact same error but fixed it by setting `ME_CONFIG_MONGODB_ENABLE_ADMIN` to `"false"` and explicitly set `ME_CONFIG_MONGODB_AUTH_DATABASE`, `ME_CONFIG_MONGODB_AUTH_USERNAME` and `ME_CONFIG_MONGODB_AUTH_PASSWORD` as mentioned by the [docker hub documentation](https://hub.docker.com/_/mongo-express/).

I'm not sure yet how to prevent the error from happening when setting `ME_CONFIG_MONGODB_ENABLE_ADMIN` to `"true"`. Seems like creating a user in `mongodb-init.js` with the `root` role for the `admin` database is not sufficient.
