### ISSUE TITLE
Unable to update document -  MongoServerError: Performing an update on the path '_id' would modify the immutable field '_id'

### ISSUE THREAD

**Issue by anowak-ct** [mongo-express/mongo-express#1360]
When I try to update a document, I am getting the following error:

```
mongodb-express  | MongoServerError: Performing an update on the path '_id' would modify the immutable field '_id'
mongodb-express  |     at /node_modules/mongodb/lib/operations/update.js:72:33
mongodb-express  |     at /node_modules/mongodb/lib/cmap/connection_pool.js:333:25
mongodb-express  |     at /node_modules/mongodb/lib/sdam/server.js:210:17
mongodb-express  |     at handleOperationResult (/node_modules/mongodb/lib/sdam/server.js:326:20)
mongodb-express  |     at Connection.onMessage (/node_modules/mongodb/lib/cmap/connection.js:243:9)
mongodb-express  |     at MessageStream.<anonymous> (/node_modules/mongodb/lib/cmap/connection.js:61:60)
mongodb-express  |     at MessageStream.emit (node:events:517:28)
mongodb-express  |     at processIncomingData (/node_modules/mongodb/lib/cmap/message_stream.js:125:16)
mongodb-express  |     at MessageStream._write (/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
mongodb-express  |     at writeOrBuffer (node:internal/streams/writable:392:12) {
mongodb-express  |   index: 0,
mongodb-express  |   code: 66,
mongodb-express  |   [Symbol(errorLabels)]: Set(0) {}
mongodb-express  | }
```

The `_id` property is the object id and is on our case of type Long

monogo-express version: 1.0.0-18 running in docker container.

Updating/Creating documents used work with earlier mongo-express versions.

**Comment by anowak-ct** [comment]
Same error with 1.0.2-20-alpine3.19
Any help would be great.

**Comment by anowak-ct** [comment]
Any noticed this ....? Any updates ....? Anyone ... ?

**Comment by rtritto** [comment]
@anowak-ct please can you try latest code on master branch?
