### ISSUE TITLE
Unable to read document with integer id

### ISSUE THREAD

**Issue by nasAtchia** [mongo-express/mongo-express#1547]
Creating a new issue in regards to this #1177. Still getting the same error on the latest Docker image.

```
GET /db/<DB_NAME>/<COLLECTION_NAME>/1 - - ms - -
/app/node_modules/bson/lib/error.js:41
var _this = _super.call(this, message) || this;
^


BSONTypeError: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
at new BSONTypeError (/app/node_modules/bson/lib/error.js:41:28)
at new ObjectId.createFromHexString (/app/node_modules/bson/lib/objectid.js:238:19)
at buildId (file:///app/lib/router.js:41:12)
at file:///app/lib/router.js:184:17
at paramCallback (/app/node_modules/express/lib/router/index.js:415:7)
at param (/app/node_modules/express/lib/router/index.js:395:5)
at paramCallback (/app/node_modules/express/lib/router/index.js:412:21)
at file:///app/lib/router.js:173:5
at paramCallback (/app/node_modules/express/lib/router/index.js:415:7)
at param (/app/node_modules/express/lib/router/index.js:395:5)
```

**Comment by nickbran** [comment]
This is causing us a lot of issues in our application and we would like to keep using mongo-express. We are having issues building a Docker image from source, do you have an ETA when this can be included in a new Docker image?

**Comment by xTudoS** [comment]
> This is causing us a lot of issues in our application and we would like to keep using mongo-express. We are having issues building a Docker image from source, do you have an ETA when this can be included in a new Docker image?

Not yet. try to build your own image from branch master and see if the error continues.

https://github.com/mongo-express/mongo-express-docker has all scripts that you need to do it

**Comment by persicsb** [comment]
> Not yet. try to build your own image from branch master and see if the error continues.
> 

I built a master version image, yet the problem persists.
