### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nickhnsn** [mongo-express/mongo-express#1613]
The webserver of mongo-express crashes when opening the edit view of a document in a database's collection with a non-default MongoDB ObjectId, e. g. ``_id: 1``:

```
mongoexpress_1  | /app/node_modules/bson/lib/error.js:41
mongoexpress_1  |         var _this = _super.call(this, message) || this;
mongoexpress_1  |                            ^
mongoexpress_1  | 
mongoexpress_1  | BSONTypeError: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
mongoexpress_1  |     at new BSONTypeError (/app/node_modules/bson/lib/error.js:41:28)
mongoexpress_1  |     at new ObjectId.createFromHexString (/app/node_modules/bson/lib/objectid.js:238:19)
mongoexpress_1  |     at buildId (file:///app/lib/router.js:41:12)
mongoexpress_1  |     at file:///app/lib/router.js:184:17
mongoexpress_1  |     at paramCallback (/app/node_modules/express/lib/router/index.js:415:7)
mongoexpress_1  |     at param (/app/node_modules/express/lib/router/index.js:395:5)
mongoexpress_1  |     at paramCallback (/app/node_modules/express/lib/router/index.js:412:21)
mongoexpress_1  |     at file:///app/lib/router.js:173:5
mongoexpress_1  |     at paramCallback (/app/node_modules/express/lib/router/index.js:415:7)
mongoexpress_1  |     at param (/app/node_modules/express/lib/router/index.js:395:5)
mongoexpress_1  | 
mongoexpress_1  | Node.js v18.20.3
````

Version: mongo-express 1.0.2, latest docker image

**Comment by nickhnsn** [comment]
From my point of view, this is a critical bug that requires a hotfix. When will the updated Docker image be released? @rtritto

**Comment by rtritto** [comment]
@nickhnsn please, can you confirm the issue with latest code from master branch?

FYI @BlackthornYugen

**Comment by ch1seL** [comment]
same problem on node.js v20 (mongo-express:1.0.2-20-alpine3.19)
```
2024-10-22T11:05:49.934208875Z Node.js v20.18.0
2024-10-22T11:05:50.946161690Z Waiting for mongo:27017...
2024-10-22T11:05:51.811755760Z No custom config.js found, loading config.default.js
2024-10-22T11:05:51.812454855Z Welcome to mongo-express 1.0.2
2024-10-22T11:05:51.812479755Z ------------------------
2024-10-22T11:05:51.812504255Z 
2024-10-22T11:05:51.812513755Z 
2024-10-22T11:05:51.872140226Z Mongo Express server listening at http://0.0.0.0:8081
2024-10-22T11:05:51.872761221Z Server is open to allow connections from anyone (0.0.0.0)
2024-10-22T11:07:25.135027801Z /app/node_modules/bson/lib/error.js:41
2024-10-22T11:07:25.135067201Z         var _this = _super.call(this, message) || this;
2024-10-22T11:07:25.135071801Z                            ^
2024-10-22T11:07:25.135074801Z 
2024-10-22T11:07:25.135077301Z BSONTypeError: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
2024-10-22T11:07:25.135080201Z     at new BSONTypeError (/app/node_modules/bson/lib/error.js:41:28)
2024-10-22T11:07:25.135082701Z     at new ObjectId.createFromHexString (/app/node_modules/bson/lib/objectid.js:238:19)
2024-10-22T11:07:25.135085201Z     at buildId (file:///app/lib/router.js:41:12)
2024-10-22T11:07:25.135087501Z     at file:///app/lib/router.js:184:17
2024-10-22T11:07:25.135102101Z     at paramCallback (/app/node_modules/express/lib/router/index.js:415:7)
2024-10-22T11:07:25.135104701Z     at param (/app/node_modules/express/lib/router/index.js:395:5)
2024-10-22T11:07:25.135106901Z     at paramCallback (/app/node_modules/express/lib/router/index.js:412:21)
2024-10-22T11:07:25.135109101Z     at file:///app/lib/router.js:173:5
2024-10-22T11:07:25.135111401Z     at paramCallback (/app/node_modules/express/lib/router/index.js:415:7)
2024-10-22T11:07:25.135113701Z     at param (/app/node_modules/express/lib/router/index.js:395:5)
```

**Comment by paniKatarinka** [comment]
Is there an available workaround if a solution has not yet been identified?

**Comment by ch1seL** [comment]
> Is there an available workaround if a solution has not yet been identified?

- download files from https://github.com/mongo-express/mongo-express-docker/tree/master/1.0/20-alpine3.19
- `docker build --build-arg MONGO_EXPRESS_VERSION=master --tag mongo-express:master .`

**Comment by persicsb** [comment]
This problem is still present in a build from the master branch. This is quite critical.

**Comment by VeltmanSander** [comment]
Is this bug already fixed?
We encounter the same problem.

**Comment by anowak-ct** [comment]
I have the same problem, because we are using Long for _id as well.  This was a bad choice in hindsight
