### ISSUE TITLE
Not able to connect to mongo db over ssl

### ISSUE THREAD

**Issue by omeruth** [mongo-express/mongo-express#1622]
momgo-express is not able to connect to mongo db over ssl  despite that other services can connect with mongo using same certificates as mongo-express. below is the error and a snippet from docker compose. mongo-express:latest also had the problem that others reported so I switched to 0.54. From the error it looks like mongo-express is still not trying to use ssl connection. I wonder if the env variables are being ignored as defined in docker-compose

mongo-express logs
Welcome to mongo-express
------------------------

Mongo Express server listening at https://0.0.0.0:8081
Server is open to allow connections from anyone (0.0.0.0)
basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!

/node_modules/mongodb/lib/server.js:265
        process.nextTick(function() { throw err; })
                                      ^
Error [MongoError]: connection 0 to mongodb_dev:27017 closed
    at Function.MongoError.create (/node_modules/mongodb-core/lib/error.js:29:11)
    at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:200:22)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:314:20)
    at TCP.<anonymous> (net.js:675:12)

docker-compose snippet     
image: mongo-express:0.54
    restart: always
    ports:
      - 8091:8081
    depends_on:
      - mongodb-finfax-dev
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: xxxxx
      ME_CONFIG_MONGODB_SERVER: mongodb_finfax_dev
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_SSL: 'true'
      ME_CONFIG_MONGODB_CA_FILE: /etc/ssl/ca.pem
      NODE_EXTRA_CA_CERTS: /etc/ssl/ca.pem
      ME_CONFIG_SITE_SSL_ENABLED: 'true'
      ME_CONFIG_SITE_SSL_CRT_PATH: /etc/ssl/crt.pem
      ME_CONFIG_SITE_SSL_KEY_PATH: /etc/ssl/key.pem
    volumes:
      - /data/app/mongocerts/crt.pem:/etc/ssl/crt.pem
      - /data/app/mongocerts/key.pem:/etc/ssl/key.pem
      - /data/app/mongocerts/ca.pem:/etc/ssl/ca.pem

**Comment by omeruth** [comment]
Additional info. This is the logs from mongodb 
"s":"I",  "c":"NETWORK",  "id":22988,   "ctx":"conn1681635","msg":"Error receiving request from client. Ending connection from remote","attr":{"error":{"code":141,"codeName":"SSLHandshakeFailed","errmsg":"The server is configured to only allow SSL connections"},"remote":"172.19.0.13:60938","connectionId":1681635}}

**Comment by omeruth** [comment]
some more info. If I use latest mongo-express image then the error is as below
(node:7) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongodb_finfax_dev:27017] on first connect [Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:94:16)
    at handleWriteReq (internal/stream_base_commons.js:53:26)
    at writeGeneric (internal/stream_base_commons.js:145:15)
    at TLSSocket.Socket._writeGeneric (net.js:787:11)
    at TLSSocket.Socket._write (net.js:799:8)
    at doWrite (_stream_writable.js:403:12)
    at clearBuffer (_stream_writable.js:542:7)
    at onwrite (_stream_writable.js:454:7)
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:103:10) {
  name: 'MongoNetworkError'
}]

**Comment by xTudoS** [comment]
Hello! @omeruth  Did you tried version from master?

**Comment by PandhuWibowo** [comment]
Somebody able to connect with TLS/SSL? I got the same issue.
