### ISSUE TITLE
Can not view document with MongoDB 3.2.0

### ISSUE THREAD

**Issue by vanduc1102** [mongo-express/mongo-express#185]
> TypeError: Cannot read property '_bsontype' of null
   at Object.exports.stringDocIDs (/root/Documents/node_modules/mongo-express/lib/filters.js:137:41)
   at eval (eval at <anonymous> (/root/Documents/node_modules/swig/lib/swig.js:498:13), <anonymous>:333:95)
   at Object.exports.each (/root/Documents/node_modules/swig/lib/utils.js:45:11)
   at eval (eval at <anonymous> (/root/Documents/node_modules/swig/lib/swig.js:498:13), <anonymous>:326:10)
   at eval (eval at <anonymous> (/root/Documents/node_modules/swig/lib/swig.js:498:13), <anonymous>:353:3)
   at Object.exports.each (/root/Documents/node_modules/swig/lib/utils.js:45:11)
   at eval (eval at <anonymous> (/root/Documents/node_modules/swig/lib/swig.js:498:13), <anonymous>:312:10)
   at Object.eval [as tpl] (eval at <anonymous> (/root/Documents/node_modules/swig/lib/swig.js:498:13), <anonymous>:361:3)
   at compiled (/root/Documents/node_modules/swig/lib/swig.js:619:18)
   at /root/Documents/node_modules/consolidate/lib/consolidate.js:415:16
   at /root/Documents/node_modules/consolidate/lib/consolidate.js:146:5
   at tryCatcher (/root/Documents/node_modules/bluebird/js/main/util.js:26:23)
   at Promise._resolveFromResolver (/root/Documents/node_modules/bluebird/js/main/promise.js:480:31)
   at new Promise (/root/Documents/node_modules/bluebird/js/main/promise.js:70:37)
   at promisify (/root/Documents/node_modules/consolidate/lib/consolidate.js:139:10)
   at Function.exports.swig.render (/root/Documents/node_modules/consolidate/lib/consolidate.js:408:10)

**Comment by wulfsolter** [comment]
Version 0.30.19 fixes this, please update :)
