### ISSUE TITLE
TypeError: Cannot read property 'avgObjSize' of undefined

### ISSUE THREAD

**Issue by halt-hammerzeit** [mongo-express/mongo-express#188]
It connects OK,
then I go to http://localhost:8081/
It displays the page.
I click "View" on the database, and it throws the exception.

(MongoDB freshly installed)

```
C:\Users\Nikolay>mongo-express -u administrator -p password -d admin
Welcome to mongo-express
------------------------


No custom config.js found, loading config.default.js
basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
Mongo Express server listening on port 8081 at localhost
Database connected
Connecting to admin...
Database admin connected
C:\Users\Nikolay\AppData\Roaming\npm\node_modules\mongo-express\node_modules\mongodb\lib\utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

TypeError: Cannot read property 'avgObjSize' of undefined
    at C:\Users\Nikolay\AppData\Roaming\npm\node_modules\mongo-express\lib\routes\database.js:17:53
    at handleCallback (C:\Users\Nikolay\AppData\Roaming\npm\node_modules\mongo-express\node_modules\mongodb\lib\utils.js:96:12)
    at C:\Users\Nikolay\AppData\Roaming\npm\node_modules\mongo-express\node_modules\mongodb\lib\db.js:299:20
    at commandCallback (C:\Users\Nikolay\AppData\Roaming\npm\node_modules\mongo-express\node_modules\mongodb-core\lib\topologies\server.js:9
29:46)
    at Callbacks.emit (C:\Users\Nikolay\AppData\Roaming\npm\node_modules\mongo-express\node_modules\mongodb-core\lib\topologies\server.js:11
6:3)
    at null.messageHandler (C:\Users\Nikolay\AppData\Roaming\npm\node_modules\mongo-express\node_modules\mongodb-core\lib\topologies\server.
js:282:23)
    at Socket.<anonymous> (C:\Users\Nikolay\AppData\Roaming\npm\node_modules\mongo-express\node_modules\mongodb-core\lib\connection\connecti
on.js:273:22)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)
```

**Comment by wulfsolter** [comment]
Very strange. What version of Mongo are you running?

    $ mongod --version

Should be getting a bit more helpful error in the latest version. What does that say?

**Comment by halt-hammerzeit** [comment]
3.2.3

I am actually using Robomongo now, seems to be an appropriate substitution

**Comment by lakshmanavaradhan** [comment]
I m also getting same error ? pls give some solution

**Comment by wulfsolter** [comment]
@lakshmanavaradhan 

What version of `mongod` are you running?
What version of `mongo-express` are you running?
Can you please paste the output shown from starting `mongo-express` all the way until the last line of error.
