### ISSUE TITLE
Failed to connect to mongo when working with docker-compose

### ISSUE THREAD

**Issue by simonlinj** [mongo-express/mongo-express#194]
Seems that when using docker-compose, the mongo server is not up and running when mongo-express trying to connect to the server. 

docker-compose.yml
``` yaml
mongoexpress:
  image: knickers/mongo-express
  ports:
    - 8081:8081
  links:
    - database
  environment:
    - ME_CONFIG_MONGODB_SERVER=database
    - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
    - ME_CONFIG_BASICAUTH_USERNAME=admin
    - ME_CONFIG_BASICAUTH_PASSWORD=pass

database:  
  image: mongo:latest
  command: mongod --smallfiles --quiet --logpath=/dev/null
```

``` log
mongoexpress_1 | Welcome to mongo-express
mongoexpress_1 | ------------------------
mongoexpress_1 |
mongoexpress_1 |
mongoexpress_1 | Server is open to allow connections from anyone (0.0.0.0)
mongoexpress_1 | Mongo Express server listening on port 8081 at 0.0.0.0
mongoexpress_1 |
mongoexpress_1 | /node_modules/mongodb/lib/server.js:242
mongoexpress_1 |         process.nextTick(function() { throw err; })
mongoexpress_1 |                                       ^
mongoexpress_1 | Error: connect ECONNREFUSED 172.17.0.2:27017
mongoexpress_1 |     at Object.exports._errnoException (util.js:856:11)
mongoexpress_1 |     at exports._exceptionWithHostPort (util.js:879:20)
mongoexpress_1 |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1053:14)
```

**Comment by wulfsolter** [comment]
Sounds like this is a problem with your configuration. Ensure that mongo is up and running before trying to connect to it.

**Comment by knickers** [comment]
I would suggest swapping the order of your compose file. Put the database definition before the mongo-express definition. :wink:

**Comment by knickers** [comment]
Also, your `links` line should look like this
```
links:
  - database:mongo
```

**Comment by knickers** [comment]
Oh. I see you defined the database name in the env var. Sorry I jumped the gun on that one :stuck_out_tongue_winking_eye:.

**Comment by knickers** [comment]
I can confirm this works:
```yml
mongo:
  image: mongo

mongoexpress:
  image: knickers/mongo-express
  links:
    - mongo
  ports:
    - 8081:8081
````

```
$ docker-compose up
Recreating docker_mongo_1...
Recreating docker_mongoexpress_1...
Attaching to docker_mongo_1, docker_mongoexpress_1
mongo_1        | 2016-03-03T02:39:31.078+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=dcc525f505bd
mongo_1        | 2016-03-03T02:39:31.078+0000 I CONTROL  [initandlisten] db version v3.2.3
mongo_1        | 2016-03-03T02:39:31.078+0000 I CONTROL  [initandlisten] git version: b326ba837cf6f49d65c2f85e1b70f6f31ece7937
mongo_1        | 2016-03-03T02:39:31.078+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.1e 11 Feb 2013
mongo_1        | 2016-03-03T02:39:31.078+0000 I CONTROL  [initandlisten] allocator: tcmalloc
mongo_1        | 2016-03-03T02:39:31.078+0000 I CONTROL  [initandlisten] modules: none
mongo_1        | 2016-03-03T02:39:31.078+0000 I CONTROL  [initandlisten] build environment:
mongo_1        | 2016-03-03T02:39:31.078+0000 I CONTROL  [initandlisten]     distmod: debian71
mongo_1        | 2016-03-03T02:39:31.078+0000 I CONTROL  [initandlisten]     distarch: x86_64
mongo_1        | 2016-03-03T02:39:31.078+0000 I CONTROL  [initandlisten]     target_arch: x86_64
mongo_1        | 2016-03-03T02:39:31.078+0000 I CONTROL  [initandlisten] options: {}
mongo_1        | 2016-03-03T02:39:31.104+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
mongo_1        | 2016-03-03T02:39:31.104+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=3G,session_max=20000,eviction=(threads_max=4),config_base=false,statistics=(fast),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),checkpoint=(wait=60,log_size=2GB),statistics_log=(wait=0),
mongo_1        | 2016-03-03T02:39:34.856+0000 I CONTROL  [initandlisten] 
mongo_1        | 2016-03-03T02:39:34.856+0000 I CONTROL  [initandlisten] ** WARNING: /sys/kernel/mm/transparent_hugepage/defrag is 'always'.
mongo_1        | 2016-03-03T02:39:34.856+0000 I CONTROL  [initandlisten] **        We suggest setting it to 'never'
mongo_1        | 2016-03-03T02:39:34.856+0000 I CONTROL  [initandlisten] 
mongo_1        | 2016-03-03T02:39:34.859+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
mongo_1        | 2016-03-03T02:39:34.859+0000 I NETWORK  [HostnameCanonicalizationWorker] Starting hostname canonicalization worker
mongo_1        | 2016-03-03T02:39:35.040+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
mongoexpress_1 | Welcome to mongo-express
mongoexpress_1 | ------------------------
mongoexpress_1 | 
mongoexpress_1 | 
mongoexpress_1 | basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
mongoexpress_1 | Server is open to allow connections from anyone (0.0.0.0)
mongoexpress_1 | Mongo Express server listening on port 8081 at 0.0.0.0
mongo_1        | 2016-03-03T02:39:39.705+0000 I NETWORK  [initandlisten] connection accepted from 172.17.0.3:47098 #1 (1 connection now open)
mongoexpress_1 | Database connected
mongoexpress_1 | Admin Database connected
```

**Comment by stevenkitter** [comment]
>>ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
you must set this param.
