### ISSUE TITLE
mongo-express broken with Node.js v6.0.0-rc.3

### ISSUE THREAD

**Issue by juergenzimmermann** [mongo-express/mongo-express#217]
I just upgraded to the latest mongo-express 0.30.49 and to Node.js v6.0.0-rc.3. When I start mongo-express I'm getting this error message:
```
C:\temp\mean-ohne-angular\node_modules\mongo-express\app.js:23
if (config.console) {
          ^

TypeError: Cannot read property 'console' of undefined
    at Object.<anonymous> (C:\temp\mean-ohne-angular\node_modules\mongo-express\app.js:23:11)
    at Module._compile (module.js:530:32)
    at Object.Module._extensions..js (module.js:539:10)
    at Module.load (module.js:445:32)
    at tryModuleLoad (module.js:404:12)
    at Function.Module._load (module.js:396:3)
    at Function.Module.runMain (module.js:564:10)
    at startup (node.js:159:18)
    at node.js:444:3
```

**Comment by juergenzimmermann** [comment]
Maybe, it's related to the PR https://github.com/mongo-express/mongo-express/pull/216 which was added before releasing 0.30.49.

**Comment by juergenzimmermann** [comment]
@wulfsolter, thank you! The issue is gone in mongo-express 0.30.51.
