### ISSUE TITLE
help me in connection 

### ISSUE THREAD

**Issue by lakshmanavaradhan** [mongo-express/mongo-express#227]
/root/mongo-express-master/app.js:17
let notifier          = updateNotifier({ pkg });
                                             ^
SyntaxError: Unexpected token }
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:935:3

And i m not using any password and usersname for mongo how to execute mongo-express command ?

thanks ,
Lakshmanavaradhan

**Comment by wulfsolter** [comment]
[*mongo-express* requires Node.js v4 or higher.](https://github.com/mongo-express/mongo-express#usage-npm--cli)

**Comment by lakshmanavaradhan** [comment]
thanks bro ..its working and I facing another issue in node app 

my node -v is v5.6.0

but node app throws error 

module.js:341
    throw err;
    ^

Error: Cannot find module '/root/app'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:140:18)
    at node.js:1001:3

**Comment by lakshmanavaradhan** [comment]
now i m getting error 

Error: Cannot find module 'cli-color'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/mongo-express-master/app.js:5:25)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)

**Comment by wulfsolter** [comment]
`cli-color` is one of the dependencies that are installed when you first installed `mongo-express`.

When you `$ npm install mongo-express` it will install all the necessary dependencies.

**Comment by lakshmanavaradhan** [comment]
hi bro ,

mongo express version 
Welcome to mongo-express
------------------------
0.30.56

mongod version 

db version v3.0.12
git version: 33934938e0e95d534cebbaff656cde916b9c3573

errors  are

cd /usr/local/lib/node_modules/mongo-express/&& node app.js

Welcome to mongo-express
------------------------


basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:8081
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:65:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:84:10)

**Comment by wulfsolter** [comment]
The error, that says "Error: listen EADDRINUSE 127.0.0.1:8081" means the address is in use. There are over 50,000 Google hits for that error.
<img width="759" alt="screen shot 2016-05-19 at 12 09 30 am" src="https://cloud.githubusercontent.com/assets/1692132/15357957/14cab2c2-1d56-11e6-8b02-61b4520f1f3c.png">


I have legitimate paying work to get on with and I feel you are asking me because you are either out of your depth with using this software or are too lazy to do simple research. If you would like to be one of my paying clients, you can contact me at wulf@wulf.co.nz and I can arrange for pretty standard consulting rates.

After 4 successive issue posts, that are not issues with `mongo-express` itself, nor a lack of documentation but PEBKAC, I would like to close this issue. Thank you for your understanding and respect for my time @lakshmanavaradhan .
