### ISSUE TITLE
admindb Population Error

### ISSUE THREAD

**Issue by Omegahorus** [mongo-express/mongo-express#254]
after using current version I got an error:

```
TypeError: Cannot read property 'listDatabases' of undefined
   at Object.updateDatabases (mongo-express\lib\db.js:64:10)
   at mongo-express\lib\router.js:82:11
   at Layer.handle [as handle_request] (mongo-express\node_modules\express\lib\router\layer.js:95:5)
   at next (mongo-express\node_modules\express\lib\router\route.js:131:13)
   at Route.dispatch (mongo-express\node_modules\express\lib\router\route.js:112:3)
   at Layer.handle [as handle_request] (mongo-express\node_modules\express\lib\router\layer.js:95:5)
   at mongo-express\node_modules\express\lib\router\index.js:277:22
   at param (mongo-express\node_modules\express\lib\router\index.js:349:14)
   at param (mongo-express\node_modules\express\lib\router\index.js:365:14)
   at Function.process_params (mongo-express\node_modules\express\lib\router\index.js:410:3)
   at next (mongo-express\node_modules\express\lib\router\index.js:271:10)
   at methodOverride (mongo-express\node_modules\method-override\index.js:65:14)
   at Layer.handle [as handle_request] (mongo-express\node_modules\express\lib\router\layer.js:95:5)
   at trim_prefix (mongo-express\node_modules\express\lib\router\index.js:312:13)
   at mongo-express\node_modules\express\lib\router\index.js:280:7
   at Function.process_params (mongo-express\node_modules\express\lib\router\index.js:330:12)
```

(using nodejs 6.4 on windows 10 64bit)

I searched why this happens:

in [lib/db.js](https://github.com/mongo-express/mongo-express/blob/master/lib/db.js#L42): with merge request #253 the `adminDb `variable is set to undefined / not defined.

in async call `db.open` it is set to a value (`db.admin()`). Cause of Async nature, the returned (with `adminDb `value of `undefined`) is executed before the db is set. 

in {lib/router.js](https://github.com/mongo-express/mongo-express/blob/master/lib/router.js) only the value of undefined exists.

on later use => Error

**Comment by chrisdamba** [comment]
Wouldn't mind having a go at this?

**Comment by dozoisch** [comment]
@chrisdamba it's all yours :)

**Comment by andrew-medvedev** [comment]
Is it doomed?

**Comment by fazelit** [comment]
I have the same problem. Please aswer.

**Comment by itxx00** [comment]
solved by starting mongo-express with -a option

**Comment by tuanho091** [comment]
> solved by starting mongo-express with -a option

What is option config my can use to starting mongo-express with -a option when I deploy on k8s?
