### ISSUE TITLE
csrf issue when setting ME_CONFIG_SITE_BASEURL

### ISSUE THREAD

**Issue by davvdg** [mongo-express/mongo-express#257]
Hi

I'm trying to use mongo express through a mesos/marathon setup provided by mesosphere dcos. The web apps exposed through this software are in a subfolder ( http://<dcos_master_ip>/service/<servicename>/..., servicename is mongoexpress in this case)
So I've tried to set the env variable  ME_CONFIG_SITE_BASEURL=/service/mongoexpress/ but this make the csrf module to fail, with a 502 error:

```
Error: misconfigured csrf
   at csrf (/node_modules/csurf/index.js:71:19)
   at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/node_modules/express/lib/router/index.js:312:13)
   at /node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/node_modules/express/lib/router/index.js:330:12)
   at next (/node_modules/express/lib/router/index.js:271:10)
   at expressInit (/node_modules/express/lib/middleware/init.js:33:5)
   at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/node_modules/express/lib/router/index.js:312:13)
   at /node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/node_modules/express/lib/router/index.js:330:12)
   at next (/node_modules/express/lib/router/index.js:271:10)
   at query (/node_modules/express/lib/middleware/query.js:49:5)
   at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/node_modules/express/lib/router/index.js:312:13)
   at /node_modules/express/lib/router/index.js:280:7
```

removing the env variable allows mango express to show up, but without all the static files, scripts and so on, making it unusable.

**Comment by trivender** [comment]
similar issue.. please help...

**Comment by albanm** [comment]
Hello,

Should this really be closed ? I have the same error with the latest docker image. For example with this docker-compose instruction : 

    mongoexpress:
      image: mongo-express:0.38.0
      environment:
        - ME_CONFIG_SITE_BASEURL=/mongo-express/

The stack :

```
Error: misconfigured csrf
   at csrf (/node_modules/csurf/index.js:71:19)
   ...
```

**Comment by jbruggem** [comment]
I have the same error as well.

**Comment by KrishnaPuppala** [comment]
Yep, same with me! Below is the code snippet,  
server.use(csrf());
server.use(function(req, res, next){
  res.cookie('XSRF-TOKEN', req.csrfToken());
  res.locals.csrftoken = req.csrfToken();
  next();
});

**Comment by margau** [comment]
Had this problem too, should work with PR #347
