### ISSUE TITLE
Can't connect to replica set

### ISSUE THREAD

**Issue by jamrizzi** [mongo-express/mongo-express#272]
I get the following error when I try and start mongo-express.

```
/home/jamrizzi/GroupThreads/mongui/node_modules/mongodb/lib/replset.js:360
          process.nextTick(function() { throw err; })
                                        ^
MongoError: no valid replicaset members found
    at Timeout.<anonymous> (/home/jamrizzi/GroupThreads/mongui/node_modules/mongodb-core/lib/topologies/replset.js:645:33)
    at tryOnTimeout (timers.js:232:11)
    at Timer.listOnTimeout (timers.js:202:5)
```

I have it configured as a replica set, and I have verified that all the information I entered is correct by trying it with the mongodb CLI.  Below is the way I have it configured.

```
  mongo = {
    db:       'admin',
    host:     [
        'rest-api-data-shard-00-00-xemv3.mongodb.net',
        'rest-api-data-shard-00-01-xemv3.mongodb.net',
        'rest-api-data-shard-00-02-xemv3.mongodb.net'
    ],
    password: 'myspecialpassword',
    port:     27017,
    ssl:      true,
    url:      'mongodb://rest-api-data-shard-00-00-xemv3.mongodb.net:27017,rest-api-data-shard-00-01-xemv3.mongodb.net:27017,rest-api-data-shard-00-02-xemv3.mongodb.net:27017/admin?replicaSet=rest-api-data-shard-0',
    username: 'myspecialusername'
  };

```

**Comment by dozoisch** [comment]
I wonder if it's because the replicaSet name is not set properly using an array of hostnames. Because basically it seems like mongo.host is used but not mongo.url. Thus the `replicaSet=rest-api-data-shard-0` is never "lost" in the process.

**Comment by jamrizzi** [comment]
I just verified that is not the issue.

```
      db = new mongodb.Db('local', new mongodb.ReplSet(host, {
          poolSize:    config.mongodb.poolSize,
          ssl:             config.mongodb.ssl,
          sslValidate: config.mongodb.sslValidate,
          sslCA:         config.mongodb.sslCA,
          replicaSet:  'rest-api-data-shard-0'
      }), {
          safe: true,
          w: 0,
          authSource: 'admin'
      });
```

**Comment by dozoisch** [comment]
@jamrizzi That snippet in your last post works or not?

**Comment by jamrizzi** [comment]
It does not work. I'm still getting the same error.

**Comment by dozoisch** [comment]
Hmmm, that's weird because that's the mongodb driver directly. Do you know what parameters in your case you would need to pass to the driver to be able to connect. If you were to use the driver natively? 

Sorry for the back and forth, but I have a replicaSet set up on my servers and I can connect to it using an array in mongo-express just fine. So I'm trying to figure out why it doesn't work for yours.

**Comment by jamrizzi** [comment]
I have verified that the firewall is open, and I can connect with the mongodb CLI.

**Comment by jamrizzi** [comment]
What's your version of NodeJS? Also, does the MongoDB driver use my installation of mongo?

**Comment by jamrizzi** [comment]
I've also pinged the servers, and I get a response.  I've even tried using the IP addresses from the pinged response.

**Comment by dozoisch** [comment]
https://github.com/christkv/mongodb-core This is the driver used. I tried with both node 4 and node 6. 

There is an open issue on the driver https://github.com/christkv/mongodb-core/issues/144 I wonder if it's related.

What do you mean by your installation of mongo?

**Comment by jamrizzi** [comment]
I have MongoDB installed on my computer.  I'm assuming that would not affect it.

As far as parameters I would need, Mongo Atlas gives me the following for a URI connection.

```
mongodb://USERNAME:PASSWORD@rest-api-data-shard-00-00-xemv3.mongodb.net:27017,rest-api-data-shard-00-01-xemv3.mongodb.net:27017,rest-api-data-shard-00-02-xemv3.mongodb.net:27017/admin?ssl=true&replicaSet=rest-api-data-shard-0&authSource=admin
```

So, I'm assuming ssl, replicaSet, and authSource for parameters.

**Comment by jamrizzi** [comment]
Is it possible to setup mongo-express to accept a URI for connection?

**Comment by dozoisch** [comment]
I just joined the project as a collaborator. I will need to check the driver documentation for that.

**Comment by jamrizzi** [comment]
I noticed that mongodb is being imported instead of mongodb-core in db.js.  Is that the correct import?

**Comment by dozoisch** [comment]
Actually you are right. Hmmm we're using the higher level driver. I wonder why we're not using the normal "url" connection, from this driver.

**Comment by jamrizzi** [comment]
How do I use the normal URL connection.  I tried implementing it the other day, but it was inside of a callback, which messed up the db.js export response.

**Comment by jamrizzi** [comment]
Hmmm, I can't find the url connection method in the mongodb driver.

**Comment by dozoisch** [comment]
It's defined right here in mongoclient https://github.com/mongodb/node-mongodb-native/blob/2.2/lib/mongo_client.js#L88. I'm trying to figure out how we could do something similar.

**Comment by dozoisch** [comment]
And here is where they do the connection itself: https://github.com/mongodb/node-mongodb-native/blob/2.2/lib/mongo_client.js#L185

**Comment by jamrizzi** [comment]
Oh, yeah, that's the connect method, not the url method, but I know what you mean.  That's what I tried implementing yesterday, but it's tricky because it has a callback and db.js wasn't built to return a callback.

**Comment by dozoisch** [comment]
Yeah the issue is at line 185 of the MongoClient. It does the open directly, so if there was a way to delay that open to do it manually like here https://github.com/mongo-express/mongo-express/blob/master/lib/db.js#L102. Then it would be fine.

**Comment by jamrizzi** [comment]
Is there a way to do that?

**Comment by dozoisch** [comment]
I can take a look at implementing this near the end of the day, as I can't at this time. But I think it's doable.

**Comment by jamrizzi** [comment]
That will just allow URI connections. It won't directly fix the issue I'm having. But it should let me connect the URI way which will let me work around the issue I'm having. Am I correct about this?

**Comment by dozoisch** [comment]
Yes, I think so. Can you try in your node console, if you use mongodb.MongoClient(url.... ) directly if it works as expected?

**Comment by jamrizzi** [comment]
Sure, I'll try that.

**Comment by jamrizzi** [comment]
It works!!!!
I can't wait till you get the URI connection working :)

**Comment by jamrizzi** [comment]
I can get this to work using async and await, but I will have to compile it first.

**Comment by jamrizzi** [comment]
I did some some work that should help you out.  I don't have it fully working yet.

https://github.com/mongo-express/mongo-express/pull/274

**Comment by dozoisch** [comment]
Alright! I'll take a look at that tonight!

**Comment by jamrizzi** [comment]
Were you able to get it working?

**Comment by dozoisch** [comment]
@jamrizzi Not yet haven't had time yet :/ Working on some infrastructure stuff

**Comment by dozoisch** [comment]
@jamrizzi I'm trying to figure something out right now. I've redeployed a new mongo cluster recently so  I'll try with this one to see if it works properly.

**Comment by jamrizzi** [comment]
What's the status with this fix?

**Comment by dozoisch** [comment]
@jamrizzi So it works on my own cluster. It's a bit hard to get a fix without being able to repro :/ My cluster doesn't use the default replicaSet name, so I'm not sure what's the issue with yours. I'm trying to figure out what's the difference in the topology between what mongoclient does and what mongo-express creates.

**Comment by jamrizzi** [comment]
So, what makes your cluster setup different than mine?  I'm using Mongo Atlas.

**Comment by dozoisch** [comment]
My cluster is deployed on aws. 1 Master, 1 replica, 1 arbiter. Connecting on it using the two hosts for master & replica. The absence of replicaSet name didn't seem to be an issue. I'm not using SSL though, because it's all an intranet.

**Comment by dozoisch** [comment]
@jamrizzi can you come on reactiflux discord? I'd like to ask a couple of questions: http://www.reactiflux.com/

**Comment by jamrizzi** [comment]
Sure thing.

**Comment by jamrizzi** [comment]
Were you ever able to fix this?

**Comment by dozoisch** [comment]
@jamrizzi Not really, as said last time I can't repro on my own replicaSets... They work just fine, so it's a bit hard to know why it doesn't work on your exact configuration. I remember there we're some SSL issues (we had to disable SSL checking), but there was more than that... and I couldn't figure out what other options we're wrong in what we pass.

**Comment by jamrizzi** [comment]
Do you know if it's specific to Mongo Cloud?

**Comment by dozoisch** [comment]
I'm not sure, and I don't have an account to test it :/! So it's a bit weird. I guess the issue is about getting the right configuration in place, and some params might not be passed properly from our side! If I had an access to a setup like that one where I could repro the issue I could fix it, but without being able to repro, it's next to impossible! So I don't know if you can create multiple DBs, but if you are able to create a "test" db on that setup with a user/password that doesn't have any data access that I could have, I would probably be able to fix it. Without it, anything I tried is a blind shot.

**Comment by spacem** [comment]
I am also using atlas and I get a "no primary found in replicaset" error. I guess because there is no place to put the replicaSet parameter? Is there some way I can get this working?

**Comment by ocasta** [comment]
We have two replica sets running on AWS. One is connected via SSL the other not. I get the error described above trying to connect to the one that requires SSL and the other one works just fine

**Comment by Dashue** [comment]
Bump another one here

**Comment by dozoisch** [comment]
As I said, I don't have a setup for mongo-atlas and I couldn't reproduce on my own replica sets. So would love to get someone that has a mongo-atlas setup that fails to try to pin point the issue.

**Comment by Dashue** [comment]
Happy to help, what's the easiest approach? Alternatively, I'm using fairly new / empty setup, so might be easy to reproduce by just creating one?

**Comment by dozoisch** [comment]
First step would be making sure that you can connect using mongo driver directly by passing the same configuration, then playing with the config parameters. The connection happens in lib/db.js so there I assume there is a config that is wrong be able to connect properly to this type of topology.

**Comment by Dashue** [comment]
I'm making calls through the mongo c# driver, and they are working.

**Comment by Dashue** [comment]
Got anywhere else to continue on this discussion? I'd be happy to let you experiment with my cluster, it's just an early stage product which I can't really continue on before I can access the data :)

**Comment by dozoisch** [comment]
you can email me at hugo.dozois at gmail dot com!

**Comment by jamrizzi** [comment]
I've worked on fixing this waaaay back in the day. Honestly, (not trying to be rude), the codebase is kinda a mess. I spent several days trying to fix it (with help from their team) with no luck. I think the best solution is to rebuild the entire project.

**Comment by dozoisch** [comment]
@jamrizzi I would say team is a big word. Current maintainers are doing it completely for free, in their free time and are not the one who created the original code base. We'd love to get more people involved in this. If someone wants to do a rewrite of the connection module it'd be really nice.

**Comment by drone1** [comment]
Oh gad, how did I end up here? Just want to tail the oplog of my database on Atlas via Meteor. Halp.

**Comment by dozoisch** [comment]
@Dashue Haven't had time yet sorry.

**Comment by Dashue** [comment]
No worries, haven't had time to work on my project anyways :)

Any guess as to when you might find the time?

**Comment by spacem** [comment]
Not sure if it is helpful but robomongo also had issues connecting to atlas which is now fixed for version 1.1
https://github.com/Studio3T/robomongo/issues/1250#issuecomment-301036770

If you still need a test system atlas has a free tier which is pretty painless to set up. Takes only a few clicks and occasional spam from their sales team.
https://www.mongodb.com/cloud/atlas

**Comment by dozoisch** [comment]
@spacem dashue sent me his credential for now, but I haven't had time to look into it. The best case scenario is still if someone who actually needs this can fix it :). I don't know much about the "connection module" as I didn't write it. So I have to investigate why it wouldn't work.

**Comment by spacem** [comment]
Ok I can submit a PR.
I made some changes and have it working and I'll commit after a little more testing. Probably tomorrow.

My preference is to support a url. Full disclosure this is mostly because I couldnt figure out how to connect to atlas using the old DB method. My solution involves a connectionString parameter which if specified just ignores all the other connection options from the config. I don't think we need extra dependencies on await, etc. It can just connect at the start then it should be connected by the time someone uses it which is how it currently works.

**Comment by Dashue** [comment]
@spacem You're the man. Just a string works for me as my use case will be taking the string I'm using in my code and just banging that on the command line as is. I did try to break the string apart to fit the parameters but that was such a clumsy approach and had no confidence in that I had done it correctly.

**Comment by dozoisch** [comment]
@spacem awesome. Thanks a lot for taking care of this!

**Comment by Dashue** [comment]
@spacem ping, how's things?
