### ISSUE TITLE
Issue when deploying on Cloud Foundry

### ISSUE THREAD

**Issue by georgibarzev** [mongo-express/mongo-express#329]
Hi, I'm trying to deploy this app on a non-Bluemix Cloud Foundry and I've updated the manifest, but I've ran into this error when deploying:

```
2017-04-04T15:28:08.99+0000 [APP/PROC/WEB/0]OUT > mongo-express@0.39.1 start /home/vcap/app
2017-04-04T15:28:08.99+0000 [APP/PROC/WEB/0]OUT > cross-env NODE_ENV=production node app
2017-04-04T15:28:09.46+0000 [APP/PROC/WEB/0]ERR module.js:341
2017-04-04T15:28:09.46+0000 [APP/PROC/WEB/0]ERR     throw err;
2017-04-04T15:28:09.46+0000 [APP/PROC/WEB/0]ERR     ^
2017-04-04T15:28:09.46+0000 [APP/PROC/WEB/0]ERR Error: Cannot find module '../build-assets.json'
2017-04-04T15:28:09.46+0000 [APP/PROC/WEB/0]ERR     at Function.Module._resolveFilename (module.js:339:15)
2017-04-04T15:28:09.46+0000 [APP/PROC/WEB/0]ERR     at Function.Module._load (module.js:290:25)
2017-04-04T15:28:09.46+0000 [APP/PROC/WEB/0]ERR     at Module.require (module.js:367:17)
2017-04-04T15:28:09.46+0000 [APP/PROC/WEB/0]ERR     at require (internal/module.js:20:19)
2017-04-04T15:28:09.46+0000 [APP/PROC/WEB/0]ERR     at Object.<anonymous> (/home/vcap/app/lib/middleware.js:8:16)
2017-04-04T15:28:09.46+0000 [APP/PROC/WEB/0]ERR     at Module._compile (module.js:413:34)
2017-04-04T15:28:09.46+0000 [APP/PROC/WEB/0]ERR     at Object.Module._extensions..js (module.js:422:10)
2017-04-04T15:28:09.46+0000 [APP/PROC/WEB/0]ERR     at Module.load (module.js:357:32)
2017-04-04T15:28:09.46+0000 [APP/PROC/WEB/0]ERR     at Function.Module._load (module.js:314:12)
2017-04-04T15:28:09.46+0000 [APP/PROC/WEB/0]ERR     at Module.require (module.js:367:17)
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR! Linux 4.4.0-71-generic
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR! argv "/home/vcap/app/.heroku/node/bin/node" "/home/vcap/app/.heroku/node/bin/npm" "star
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR! node v5.12.0
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR! npm  v3.8.6
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR! code ELIFECYCLE
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR! mongo-express@0.39.1 start: `cross-env NODE_ENV=production node app`
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR! Exit status 1
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR!
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR! Failed at the mongo-express@0.39.1 start script 'cross-env NODE_ENV=production node app
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR! If you do, this is most likely a problem with the mongo-express package,
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR! not with npm itself.
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR! Tell the author that this fails on your system:
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR!     cross-env NODE_ENV=production node app
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR! You can get information on how to open an issue for this project with:
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR!     npm bugs mongo-express
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR! Or if that isn't available, you can get their info via:
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR!     npm owner ls mongo-express
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR! There is likely additional logging output above.
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR! Please include the following file with any support request:
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]ERR npm ERR!     /home/vcap/app/npm-debug.log
2017-04-04T15:28:09.48+0000 [APP/PROC/WEB/0]OUT Exit status 1
```
Do you have any suggestions how I can get around that?

Thanks in advance.
Georgi

**Comment by dozoisch** [comment]
This would be due to the build-assets.json not being there. Which is weird because I just install the 0.39.1 locally in my node_modules and that file is there. 

So the file that is missing is generated in prepublish. Can you tell me more about how you did install the module?

**Comment by georgibarzev** [comment]
Normally when deploying to Cloud Foundry you don't install the dependencies first and you just 'push' (i.e. without the node_modules directory) while the platform itself recognises the programming language and runs the necessary setup. In this case, I ran npm install locally to create the build-assets.json dependency file and tried deploying after that. 

The build-assets.json issue seems resolved that way, but now I can now see another error I've pasted below, which has to do with the config.js/config.default.js file. Do I need to edit that file for it to work? 

I've updated the manifest.yml according to my environment setup, but I'm not sure if the credentials will be picked up from the correct VCAP_SERVICES environment variables. 

Thanks in advance.

```
2017-04-05T10:03:12.03+0100 [APP/PROC/WEB/0]OUT > mongo-express@0.39.1 start /home/vcap/app
2017-04-05T10:03:12.03+0100 [APP/PROC/WEB/0]OUT > cross-env NODE_ENV=production node app
2017-04-05T10:03:12.53+0100 [APP/PROC/WEB/0]ERR Unable to load config.js!
2017-04-05T10:03:12.53+0100 [APP/PROC/WEB/0]ERR Error is:
2017-04-05T10:03:12.53+0100 [APP/PROC/WEB/0]OUT TypeError: Cannot read property 'host' of undefined
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR! Linux 4.4.0-71-generic
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR! argv "/home/vcap/app/.heroku/node/bin/node" "/home/vcap/app/.heroku/node/bin/npm" "start"
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR! node v5.12.0
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR! npm  v3.8.6
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR! code ELIFECYCLE
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR! mongo-express@0.39.1 start: `cross-env NODE_ENV=production node app`
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR! Exit status 1
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR! 
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR! Failed at the mongo-express@0.39.1 start script 'cross-env NODE_ENV=production node app'.
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR! If you do, this is most likely a problem with the mongo-express package,
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR! not with npm itself.
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR! Tell the author that this fails on your system:
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR!     cross-env NODE_ENV=production node app
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR! You can get information on how to open an issue for this project with:
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR!     npm bugs mongo-express
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR! Or if that isn't available, you can get their info via:
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR!     npm owner ls mongo-express
2017-04-05T10:03:12.54+0100 [APP/PROC/WEB/0]ERR npm ERR! There is likely additional logging output above.
2017-04-05T10:03:12.55+0100 [APP/PROC/WEB/0]ERR npm ERR! Please include the following file with any support request:
2017-04-05T10:03:12.55+0100 [APP/PROC/WEB/0]ERR npm ERR!     /home/vcap/app/npm-debug.log
2017-04-05T10:03:12.55+0100 [APP/PROC/WEB/0]OUT Exit status 1
```

**Comment by dozoisch** [comment]
It is likely that this thing returns undefined.  (in config.default.js). This might be due to a change in the way the env variable is set up. 

```
if (process.env.VCAP_SERVICES) {
  var dbLabel = 'mongodb-2.4';
  var env = JSON.parse(process.env.VCAP_SERVICES);
  if (env[dbLabel]) {
    mongo = env[dbLabel][0].credentials;
  }
}
```

Can you try with dbLabel `mongodb` instead of mongodb-2.4. Someone had reported that, but never followed through so it was never changed. https://github.com/mongo-express/mongo-express/issues/240

**Comment by dozoisch** [comment]
Since there is no reply I will close this issue. Feel free to ping me and I will reopen it but until there is more information I can't do anything.

**Comment by cfmagnum** [comment]
Hi @dozoisch 

Sorry for the slow reply. I've just tested it with the change in config.default.js that you suggested. I'm getting a different error now:

```
2017-05-02T09:42:52.10+0000 [APP/PROC/WEB/0]OUT Mongo Express server listening at http://0.0.0.0:8080
2017-05-02T09:42:52.10+0000 [APP/PROC/WEB/0]ERR Server is open to allow connections from anyone (0.0.0.0)
2017-05-02T09:42:52.10+0000 [APP/PROC/WEB/0]ERR basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
2017-05-02T09:42:53.10+0000 [APP/PROC/WEB/0]ERR /home/vcap/app/node_modules/mongodb/lib/server.js:265
2017-05-02T09:42:53.10+0000 [APP/PROC/WEB/0]ERR         process.nextTick(function() { throw err; })
2017-05-02T09:42:53.10+0000 [APP/PROC/WEB/0]ERR                                       ^
2017-05-02T09:42:53.10+0000 [APP/PROC/WEB/0]ERR MongoError: failed to connect to server [*.*.*.*:27017] on first connect
2017-05-02T09:42:53.10+0000 [APP/PROC/WEB/0]ERR     at Pool.<anonymous> (/home/vcap/app/node_modules/mongodb-core/lib/topologies/server.js:326:35)
2017-05-02T09:42:53.10+0000 [APP/PROC/WEB/0]ERR     at emitOne (events.js:96:13)
2017-05-02T09:42:53.10+0000 [APP/PROC/WEB/0]ERR     at Pool.emit (events.js:191:7)
2017-05-02T09:42:53.10+0000 [APP/PROC/WEB/0]ERR     at Connection.<anonymous> (/home/vcap/app/node_modules/mongodb-core/lib/connection/pool.js:270:12)
2017-05-02T09:42:53.10+0000 [APP/PROC/WEB/0]ERR     at Object.onceWrapper (events.js:293:19)
2017-05-02T09:42:53.10+0000 [APP/PROC/WEB/0]ERR     at emitTwo (events.js:106:13)
2017-05-02T09:42:53.10+0000 [APP/PROC/WEB/0]ERR     at Connection.emit (events.js:194:7)
2017-05-02T09:42:53.10+0000 [APP/PROC/WEB/0]ERR     at Socket.<anonymous> (/home/vcap/app/node_modules/mongodb-core/lib/connection/connection.js:175:49)
2017-05-02T09:42:53.10+0000 [APP/PROC/WEB/0]ERR     at Object.onceWrapper (events.js:293:19)
2017-05-02T09:42:53.10+0000 [APP/PROC/WEB/0]ERR     at emitOne (events.js:96:13)
2017-05-02T09:42:53.11+0000 [APP/PROC/WEB/0]ERR npm ERR! code ELIFECYCLE
2017-05-02T09:42:53.11+0000 [APP/PROC/WEB/0]ERR npm ERR! errno 1
```

I assume that is a problem when the mongo-express app can't connect to the db. For reference, this is the environment variable format containing the credentials to mongo that is being used within Cloud Foundry. Is there anything I need to change in how that is being passed within mongo-express?

```
{
 "VCAP_SERVICES": {
  "mongodb": [
   {
    "credentials": {
     "database": "*",
     "host": "*",
     "password": "*",
     "port": "*",
     "scheme": "mongodb",
     "uri": "mongodb://*",
     "username": "*"
    },
    "label": "mongodb",
    "name": "my-mongo",
    "plan": "standard",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [],
    "volume_mounts": []
   }
  ]
 }
}
```
Regards,
Georgi

**Comment by dozoisch** [comment]
See 

https://github.com/mongo-express/mongo-express/blob/master/config.default.js#L13-L30

Create your own config.js, and then remap the Cloud Foundry parameters to have the same shape as the object just below `db, host, password, port, ssl, url, username`!

**Comment by cfmagnum** [comment]
Thanks @dozoisch 

Changing that section of the config file and remapping the object to the Cloud Foundry environment variables fixed the problem and it's working now! Thanks again for the help.

I have one more question: is the feature of importing json files to the collections something that you are planning on adding to the tool?

Thanks
Georgi

**Comment by dozoisch** [comment]
I don't really have the time to do it, but I would love a PR if this is something important for you / your clients!
