### ISSUE TITLE
Fatal error while exporting in csv

### ISSUE THREAD

**Issue by ricpet** [mongo-express/mongo-express#346]
I am trying to test the "Export --CSV" for a collection but I get the following error: 

**FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory**

**Comment by ricpet** [comment]
I tried to run the app by increasing the memory with "node --max_old_space_size=8192 app.js 
" and now the error is:

**Comment by janusd** [comment]
Might be similar to #345 as the csv export also uses toArray (see. [exp.exportCsv@collection.js](https://github.com/mongo-express/mongo-express/blob/fbbe9c7da2dc8f27a8241c5277aedb1e3d96e803/lib/routes/collection.js#L309-L316) )

**Comment by agolomoodysaada** [comment]
I'm experiencing similar issues

```
/node_modules/mongodb/lib/utils.js:98
    process.nextTick(function() { throw err; });
                                  ^

Error: params should include "fields" and/or non-empty "data" array of objects
    at checkParams (/node_modules/json2csv/lib/json2csv.js:95:11)
    at module.exports (/node_modules/json2csv/lib/json2csv.js:48:5)
    at module.exports (/node_modules/mongo-express/lib/csv.js:23:10)
    at /node_modules/mongo-express/lib/routes/collection.js:394:17
    at handleCallback (/node_modules/mongodb/lib/utils.js:95:56)
    at /node_modules/mongodb/lib/cursor.js:852:16
    at handleCallback (/node_modules/mongodb-core/lib/cursor.js:171:5)
    at setCursorNotified (/node_modules/mongodb-core/lib/cursor.js:515:3)
    at /node_modules/mongodb-core/lib/cursor.js:590:16
    at queryCallback (/node_modules/mongodb-core/lib/cursor.js:232:18)
```

**Comment by rtritto** [comment]
I tested and work.
This should be fixed, can be closed.

FYI @ricpet @agolomoodysaada @shakaran @BlackthornYugen
