### ISSUE TITLE
Version 0.42.0: Error connecting ...

### ISSUE THREAD

**Issue by MongoExpUser** [mongo-express/mongo-express#351]
Got the following error messages while connecting to mongo-express (Version 0.42.0)

node_modules/mongo-express/node_modules/mongodb/lib/mongo_client.js:367
            throw err
            ^
TypeError: db is not a function*
    at ...../node_modules/mongo-express/lib/db.js:114:53
    at Array.forEach (native)
    at setupAuthDatabases (......../node_modules/mongo-express/lib/db.js:111:25)
    at processOpenDatabase (......./node_modules/mongo-express/lib/db.js:158:9)
    at connectCallback (........./node_modules/mongo
                express/node_modules/mongodb/lib/mongo_client.js:426:5)
    at ........./node_modules/mongo-express/node_modules/mongodb/lib/mongo_client.js:364:13
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by dozoisch** [comment]
What kind of connection parameters are you using? connection string or object? 

DB seems to be undefined when the connection to the database fails.

**Comment by MongoExpUser** [comment]
dozoisch,
Thank you for your reply.

1) I was originally using "object" for connection in the config.js file:

2) I am now able to connect when I changed to "connection String" like this as suggested for version 0.42.0:

connectionString: process.env.ME_CONFIG_MONGODB_SERVER ? '' : process.env.ME_CONFIG_MONGODB_URL || 'mongodb://dbUser:pasd@domainname.com':27017'/dbName?ssl=false,


3) When I tried to access mongo-express through:   https://domainname.com:8081, I got the following new set of errors:


TypeError: Cannot read property 'listDatabases' of undefined
    at Object.connectionData.updateDatabases (......../node_modules/mongo-express/lib/db.js:41:10)
    at ......../node_modules/mongo-express/lib/router.js:94:11
    at Layer.handle [as handle_request] (......../node_modules/mongo-express/node_modules/express/lib/router/layer.js:95:5)
    at next (......../node_modules/mongo-express/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (......../node_modules/mongo-express/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (......../node_modules/mongo-express/node_modules/express/lib/router/layer.js:95:5)
    at ......../node_modules/mongo-express/node_modules/express/lib/router/index.js:277:22
    at param (......../node_modules/mongo-express/node_modules/express/lib/router/index.js:349:14)
    at param (......../node_modules/mongo-express/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (......../node_modules/mongo-express/node_modules/express/lib/router/index.js:410:3)


I am not sure if I am doing anthing wrong.

**Comment by dozoisch** [comment]
Glad it works!
