### ISSUE TITLE
Cannot find module '../build-assets.json'

### ISSUE THREAD

**Issue by aneesh-ch** [mongo-express/mongo-express#369]
module.js:471
    throw err;
    ^

Error: Cannot find module '../build-assets.json'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/node_modules/mongo-express/lib/middleware.js:8:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

**Comment by liuyidl** [comment]
May I ask how it was resolved
