### ISSUE TITLE
ForbiddenError: invalid csrf token

### ISSUE THREAD

**Issue by PHPHa** [mongo-express/mongo-express#412]
```
ForbiddenError: invalid csrf token
   at csrf (/data/wwwroot/mongo.xxx.com/node_modules/csurf/index.js:112:19)
   at Layer.handle [as handle_request] (/data/wwwroot/mongo.xxx.com/node_modules/express/lib/router/layer.js:95:5)
   at trim_prefix (/data/wwwroot/mongo.xxx.com/node_modules/express/lib/router/index.js:312:13)
   at /data/wwwroot/mongo.xxx.com/node_modules/express/lib/router/index.js:280:7
   at Function.process_params (/data/wwwroot/mongo.xxx.com/node_modules/express/lib/router/index.js:330:12)
   at next (/data/wwwroot/mongo.xxx.com/node_modules/express/lib/router/index.js:271:10)
   at Immediate.<anonymous> (/data/wwwroot/mongo.xxx.com/node_modules/express/lib/application.js:232:9)
   at Immediate.<anonymous> (/data/wwwroot/mongo.xxx.com/node_modules/express/lib/router/index.js:618:15)
   at runCallback (timers.js:674:20)
   at tryOnImmediate (timers.js:645:5) 
```

### The solution is as follows:
`# vim node_modules/mongo-express/lib/views/document.html`
**replace 'onclick="return history.back()"' with 'onclick="return onBackClick()"'**

**Comment by PHPHa** [comment]
### The solution is as follows:

`# vim node_modules/mongo-express/lib/views/document.html`
**replace 'onclick="return history.back()"' with 'onclick="return onBackClick()"'**

**Comment by beatgrabe** [comment]
Still on `0.49.0`
