### ISSUE TITLE
import does not work on json arrays files.

### ISSUE THREAD

**Issue by positron96** [mongo-express/mongo-express#433]
Gives 
```
{ MongoError: operation passed in cannot be an Array
mongo-express_1  |     at Function.MongoError.create (/node_modules/mongodb-core/lib/error.js:31:11)
mongo-express_1  |     at toError (/node_modules/mongodb/lib/utils.js:114:22)
mongo-express_1  |     at addToOperationsList (/node_modules/mongodb/lib/bulk/unordered.js:182:11)
mongo-express_1  |     at UnorderedBulkOperation.raw (/node_modules/mongodb/lib/bulk/unordered.js:387:7)
mongo-express_1  |     at bulkWrite (/node_modules/mongodb/lib/collection.js:636:12)
mongo-express_1  |     at /node_modules/mongodb/lib/collection.js:530:5
mongo-express_1  |     at new Promise (<anonymous>)
mongo-express_1  |     at Collection.insertMany (/node_modules/mongodb/lib/collection.js:529:10)
mongo-express_1  |     at Collection.insert (/node_modules/mongodb/lib/collection.js:825:15)
mongo-express_1  |     at keys.forEach (/node_modules/mongo-express/lib/routes/collection.js:582:24)
mongo-express_1  |   name: 'MongoError',
mongo-express_1  |   message: 'operation passed in cannot be an Array',
mongo-express_1  |   driver: true }
```

I have latest docker image of mongo-express (0.49).

Actually, there are 3 export buttons in the UI and it not clear what should I pass into import. Anyway, I tried all of them, none work. json array gives most info on console, others silently give http 400.

**Comment by wakabayashik** [comment]
https://github.com/mongo-express/mongo-express/blob/797e68de25e3566f658b3691ddbb2aac20e393c0/lib/routes/collection.js#L576-L577

I modified collection.js in my working clone and it works for me...
```javascript
var fileContent = req.files[key].data.toString('utf8');
if (fileContent.slice(0,1) === '[' && fileContent.slice(-1) === ']') fileContent = fileContent.slice(1,-1);
const str = `[${fileContent.replace(/}[\r\n]{1,2}(\s)?\{/gm, '},{').replace(/\{\s*"\$oid"\s*:\s*"(.+?)"\s*}/gm, '"$1"')}]`;
```

**Comment by smn-snkl** [comment]
Is this working now? I still can't get imports to work ...

**Comment by PabloSzx** [comment]
I am getting the same error: "MongoError: operation passed in cannot be an Array" i used the modification and doesnt help at all

**Comment by dozoisch** [comment]
@mike442144 You probably have the most knowledge about this :)

**Comment by smn-snkl** [comment]
@mike442144 but it doesn't work with mongo-express' own export function, right? I tried to export one collection using the export button, and importing it again using the import button

**Comment by mike442144** [comment]
@smn-snkl Yep, I just created a pull request.

**Comment by sonarun** [comment]
I updated my docker image to 51.2 and I still can't get the imports and exports to work

**Comment by anthony-o** [comment]
> I updated my docker image to 51.2 and I still can't get the imports and exports to work..
> ![screen shot 2019-02-18 at 1 07 46 pm](https://user-images.githubusercontent.com/593557/52950012-346d8780-337e-11e9-8a41-a8c1605fedaa.jpg)
I have the same error, I was thinking perhaps one fix would be to remove the `"_id"` field of each objects before passing them to MongoDB?

**Comment by anthony-o** [comment]
Or import it by converting it first with `json2mongo` according to [this bug resolution](https://jira.mongodb.org/browse/NODE-91)?

**Comment by pista37** [comment]
I still can not use the import function.
Please state that the import feature is not supported or remove the import button.

**Comment by dozoisch** [comment]
@pista37 we also accept PRs

**Comment by haliliceylan** [comment]
![image](https://user-images.githubusercontent.com/33789758/65369430-53eeca80-dc55-11e9-8eef-53f9bc7c417a.png)
same here

**Comment by ddurham2** [comment]
I also cannot get import to work.  Seems like a pretty broken feature at the moment.

**Comment by tanoabeleyra** [comment]
If I export with the "standard" option then on import it fails saying `Error: key $oid must not start with '$'`. If I export as a "jsonArray" then it fails saying `operation passed in cannot be an Array`.

`mongoimport --jsonArray` is working, but I would prefer to use Mongo Express.

**Comment by PathToLife** [comment]
Like wakabayashik commented above. @wakabayashik 

The Json document needs to change keys to $oid -> $1.
The regex to do so doesn't work with spaces
`{[space]"$oid":[space] {}[space]}` is not detected by the original regex string.

`\{"\$oid":"(.+?)"}`

The fix is: 
`\{\s*"\$oid"\s*:\s*"(.+?)"\s*}`

I've just successfully imported a somewhat convoluted user data document without errors

**Comment by d-ivashchuk** [comment]
Any updates on this issue? I mean native import support from files generated via `export` buttons. I've seen the discussion and that there were some fixes merged, but it seems still not to be working in 2021.

Cheers for maintaining this amazing library -  this function working and I would be the happiest user of this mongo db manager :D

**Comment by nesa-1968** [comment]
Hello,
I first made an export from a local MongoDB into a file and the import worked after removing `ISODate(...)`, and leaving the date string that has to have ISO format `"2020-03-30T00:00:00.000Z"`, including 3 digits before `Z`.
Then I made a mongo-express export to a file and deleted all documents in the collection.
In the newly exported file I have first removed square brackets, since import creates its own array. 
Then with `regexp `in Notepad++, I have changed something like `"someKey":{"$date":"2020-03-16T08:16:06Z"}` to `"someKey": "2020-03-16T08:16:06.000Z"`. Note the last 3 digits before `Z`.
Import worked again. Hope it will work for you as well. My version of mongo-express is from June 2020.

**Comment by nesa-1968** [comment]
Hello, 
Based on this [blog post](https://weblog.west-wind.com/posts/2014/jan/06/javascript-json-date-parsing-and-real-dates) I made it work after changing the function `importCollection` in `<MONGO-EXPRESS>\lib\routes\collection.js` by adding the following filter function to `JSON.parse` call:
```
        const arr = JSON.parse(str, (key, value) => {
            if (typeof value === 'string') {
                const reISO = /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:Z|(\+|-)([\d|:]*))?$/;
                const reMsAjax = /^\/Date\((d|-|.*)\)[\/|\\]$/;
                let a = reISO.exec(value);
                if (a)
                    return new Date(value);
                a = reMsAjax.exec(value);
                if (a) {
                    const b = a[1].split(/[-+,.]/);
                    return new Date(b[0] ? +b[0] : 0 - +b[1]);
                }
            }
            return value;
        });
```
Respective value should be just regular ISO string, like `"someKey": "2020-03-30T00:00:00Z"`. So, a little `RegExp `"find&replace" in Notepad++ is needed. Do not forget to restart the Node.js.

**Comment by Kyle772** [comment]
Seems like there are a lot of seemingly hacky solutions to this problem. 
Why can mongo-express export to a format and not import the same format? Seems extremely convoluted.

Steps to manually avoid this on docker
1) Export JSON from mongoexpress
2) Copy exported json into mongodb container
`docker cp <src-import-file> <mongodb container name>:<import destination>`
3) Authenticate into mongodb container and import using mongoimport
`docker-compose exec <mongodb container name> mongoimport --jsonArray --username=<user> --password=<pass> -d <database> -c <collection> <import destination>`

I got an authentication error despite using the right info in what I assume is an unrelated problem. I ended up copying over my db entries by hand using "New Document" with each item because it was far faster than trying to figure out what was happening but maybe the above will help someone. If there are any maintainers looking through here PLEASE address this bug. I straight up would've gone with another mongo gui had I known the json import/export didn't work. Very misleading to even have that button if there's no way to import without jumping through a ton of hoops.

**Comment by gustavocoleta** [comment]
the @Kyle772 response works for me

**Comment by MZanggl** [comment]
This is already fixed in the master branch https://github.com/mongo-express/mongo-express/pull/789

@dozoisch  Do you already have a plan for when's the next release?

**Comment by matthe68** [comment]
So you're telling me that after 4 years of this issue being open Compass has not fixed their interface to actually allow these imports?

**Comment by rcaldas-com** [comment]
Import of exported collections still doesn't work.

**Comment by RensTillmann** [comment]
For all of you that are struggling with export/import, I think the simplest way to fix this is to just open vim. Then start a macro, do the edits whatever it might be. Then repeat it for the whole document. As an example, let's assume the below export content. It contains the object ID, and a date value `lastModified`. If you have a pretty format you will first want to minify the output with a simple tool like: https://www.cleancss.com/json-minify/ otherwise the macro that I use will not work.

```
[{"_id":{"$oid":"632b3b44d88c0a88eb307481"},"lastModified":{"$date":"2022-10-06T03:58:14.291Z"}},{"_id":{"$oid":"632b3b44d88c0a88eb307482"},"lastModified":{"$date":"2022-10-07T03:58:14.291Z"}},{"_id":{"$oid":"632b3b44d88c0a88eb307483"},"lastModified":{"$date":"2022-10-08T03:58:14.291Z"}}]
```

To make this import file work, you will need to remove the `$oid` and also replace the `$date` with `ISODate()`. If your export file contains other keys you will have to do the same thing for them. But for this specific example I use the below macro:

```
First open the file in vim editor

qq       (to start macro under letter q)

/\$oid   (start a forward search for $oid)
f:       (search for next colon)
,        (reverse search for previous colon)
l        (go one position/char to the right)
v        (visual mode)
f:       (search for next colon)
d        (delete selection)
f}       (find closing curly brace)
x        (remove the curly brace)

/\$date  (start a forward search for $date)
f:       (search for next colon)
,        (reverse search for previous colon)
l        (go one position/char to the right)
v        (visual mode)
f:       (search for next colon)
s        (start substitution)
ISODate(
ESC      (exit insert mode)
f}       (find closing curly brace)
s        (start substitution)
)        
q        (stop the recording)

1000@q   (depending on how large your export is, you can define to execute it X times. In this case I execute the macro a thousand times.).
```

I guess if you need to do export/import often, then you might want to write a simple script in whatever language you prefer, and execute the same search/replace. For me above is sufficient for those few occasions.

**Comment by RobertoMaurizzi** [comment]
I installed the container to import a csv file into a new collection... what a waste of time.
If you need to do that, copy the csv file in the container (or in a directory bound to somewhere inside the container) then run
```
mongoimport --type=csv --headerline --authenticationDatabase admin -d yourdb -c thecollection --uri=mongodb://theuser:thepassword@127.0.0.1:27017  thefile.csv
```

**Comment by David263** [comment]
I installed Community MongoDB on my local Windows server, then used Compass to import this JSON test file:
```
{
	"_id": "111112",
	"name": "art",
	"orders": []
}

```
The result was an error: Operation passed in cannot be an Array

This is not a good error message, because it is unclear what the Operation or Array are. Since this is standard JSON, I do not expect an error message.

**Comment by RensTillmann** [comment]
@David263 perhaps this info helps in your case: https://www.mongodb.com/community/forums/t/import-a-embedded-json-document-with-compass-error-operation-passed-in-cannot-be-an-array/154021/2

**Comment by David263** [comment]
[Rens Tillmann](https://github.com/RensTillmann), No, this doesn't help because the problem doesn't appear similar. Also, no solution is presented. It turns out that Compass requires an array of JSON objects as input, but this fact is not mentioned in their training course and is not explained by the above error message. The error message should be improved.

**Comment by RensTillmann** [comment]
No clue about the tool you use, but perhaps try this (wrap your object into array):
```
[{
	"_id": "111112",
	"name": "art",
	"orders": []
}]
```

**Comment by ivanvmoreno** [comment]
> No clue about the tool you use, but perhaps try this (wrap your object into array):
> 
> ```
> [{
> 	"_id": "111112",
> 	"name": "art",
> 	"orders": []
> }]
> ```

That did the trick for me!

**Comment by David263** [comment]
Yes, that worked for me, too. Either Compass needs to be changed to allow a single object to be inserted, or the error message should be completely changed to explain what format the data must use. There is no excuse for such a hurdle for newcomers to Compass, in my opinion.

**Comment by Lane-humidity** [comment]
> So you're telling me that after 4 years of this issue being open Compass has not fixed their interface to actually allow these imports?





https://nodeer.space/questions/retrieve-documents-from-mongodb-where-the-array-includes-a-specific-field-within-a-document

**Comment by David263** [comment]
I gave up on using Mongo when I encountered this issue. I have since created my own database interface for using JavaScript databases in my programs (I don't bother using schemas for simplicity). Then, after being annoyed by all the quotation marks required by JSON, whether needed or not, I created my own structured data language.

Just in case you are interested, here is an example of the language:

`object
|   name: example
|   field1: array
|   |   C
|   |   D
|   strings: object
|   |   a: This is an unquoted string value
|   |   b: "This is a quoted string"
`

Off-topic, for sure, but I just wanted to show that my difficulties understanding Mongo led me to something that works for me better.

**Comment by habutre** [comment]
Hey all,

I have similar issues then here are the things I have found and the ones that work for me:

1. I was trying to import regular JSON created from `mongoexport` and it does not work
2. I make it work by passing `--jsonArray` to `mongoexport` commandline tool
3. Using the collections exported from Mongo Compass also does not work besides being generated as JSON Array, so I realize that Mongo Compass generates the export in _pretty_ format instead of _compressed_ one generated by `mongoexport` cmdline tool, to make it work I replaced newlines using vim substitution command `:,%s/\n//g` and voilà it worked

This issue brings lots of helpful insights #1225
