### ISSUE TITLE
Install with docker on plesk

### ISSUE THREAD

**Issue by simplewebit** [mongo-express/mongo-express#434]
I have setup my mongodb docker image on my plesk server with ubuntu 14.04 LTS. All is ok about mongo. I can access from shell and from robot 3t. I need to use mongo express to manage mongo db from web based interface and i have this error log and i can't use the system.

	Waiting for mongo:27017...
	Fri Sep 28 19:22:57 UTC 2018 retrying to connect to mongo:27017 (2/5)
	Fri Sep 28 19:23:03 UTC 2018 retrying to connect to mongo:27017 (3/5)
	Fri Sep 28 19:23:09 UTC 2018 retrying to connect to mongo:27017 (4/5)
	Fri Sep 28 19:23:15 UTC 2018 retrying to connect to mongo:27017 (5/5)
	Welcome to mongo-express
	------------------------

	Mongo Express server listening at http://0.0.0.0:8081
	/docker-entrypoint.sh: line 14: mongo: Try again
	/docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
	/docker-entrypoint.sh: line 14: mongo: Try again
	/docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
	/docker-entrypoint.sh: line 14: mongo: Try again
	/docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
	/docker-entrypoint.sh: line 14: mongo: Try again
	/docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
	/docker-entrypoint.sh: line 14: mongo: Try again
	/docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
	[31mServer is open to allow connections from anyone (0.0.0.0)[39m

	/node_modules/mongodb/lib/server.js:265
			process.nextTick(function() { throw err; })
										  ^
	MongoError: failed to connect to server [mongo:27017] on first connect
		at Pool.<anonymous> (/node_modules/mongodb-core/lib/topologies/server.js:326:35)
		at emitOne (events.js:116:13)
		at Pool.emit (events.js:211:7)
		at Connection.<anonymous> (/node_modules/mongodb-core/lib/connection/pool.js:270:12)
		at Object.onceWrapper (events.js:317:30)
		at emitTwo (events.js:126:13)
		at Connection.emit (events.js:214:7)
		at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:175:49)
		at Object.onceWrapper (events.js:315:30)
		at emitOne (events.js:116:13)

Any advice?

**Comment by dozoisch** [comment]
Seems like your mongo url is not good. I would look into your connection settings. They can be set from env variable or from a config file.

**Comment by simplewebit** [comment]
@dozoisch what do you need to investigate?

**Comment by simplewebit** [comment]
> Seems like your mongo url is not good. I would look into your connection settings. They can be set from env variable or from a config file.

You can see the setting from this https://i.stack.imgur.com/yWOWD.png

**Comment by mohamedbrahimi** [comment]
i have the same issues, any solution ?

**Comment by crossSulation** [comment]
mongo:
    container_name: mongo_db
    image: mongo
    volumes:
      - ./data/mongo/:/var/lib/mongodb
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root123
      ME_CONFIG_MONGODB_AUTH_USERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root123
      ME_CONFIG_MONGODB_SERVER: localhost
Dockerfile config
error
Waiting for localhost:27017...
/docker-entrypoint.sh: connect: Address not available
/docker-entrypoint.sh: line 14: /dev/tcp/localhost/27017: Address not available
Fri Dec 14 06:36:07 UTC 2018 retrying to connect to localhost:27017 (2/5)
/docker-entrypoint.sh: connect: Address not available
/docker-entrypoint.sh: line 14: /dev/tcp/localhost/27017: Address not available
Fri Dec 14 06:36:08 UTC 2018 retrying to connect to localhost:27017 (3/5)
/docker-entrypoint.sh: connect: Address not available
/docker-entrypoint.sh: line 14: /dev/tcp/localhost/27017: Address not available
Fri Dec 14 06:36:09 UTC 2018 retrying to connect to localhost:27017 (4/5)
/docker-entrypoint.sh: connect: Address not available
/docker-entrypoint.sh: line 14: /dev/tcp/localhost/27017: Address not available
Fri Dec 14 06:36:10 UTC 2018 retrying to connect to localhost:27017 (5/5)
/docker-entrypoint.sh: connect: Address not available
/docker-entrypoint.sh: line 14: /dev/tcp/localhost/27017: Address not available
Welcome to mongo-express
------------------------


Mongo Express server listening at http://0.0.0.0:8081
Server is open to allow connections from anyone (0.0.0.0)

/node_modules/mongodb/lib/server.js:265
        process.nextTick(function() { throw err; })
                                      ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
/docker-entrypoint.sh: connect: Address not available
/docker-entrypoint.sh: line 14: /dev/tcp/localhost/27017: Address not available
Waiting for localhost:27017...
/docker-entrypoint.sh: connect: Address not available
/docker-entrypoint.sh: line 14: /dev/tcp/localhost/27017: Address not available
Fri Dec 14 06:36:13 UTC 2018 retrying to connect to localhost:27017 (2/5)
Fri Dec 14 06:36:14 UTC 2018 retrying to connect to localhost:27017 (3/5)
/docker-entrypoint.sh: connect: Address not available
/docker-entrypoint.sh: line 14: /dev/tcp/localhost/27017: Address not available
Fri Dec 14 06:36:15 UTC 2018 retrying to connect to localhost:27017 (4/5)
/docker-entrypoint.sh: connect: Address not available
/docker-entrypoint.sh: line 14: /dev/tcp/localhost/27017: Address not available
/docker-entrypoint.sh: connect: Address not available
Fri Dec 14 06:36:16 UTC 2018 retrying to connect to localhost:27017 (5/5)
/docker-entrypoint.sh: line 14: /dev/tcp/localhost/27017: Address not available
Welcome to mongo-express
------------------------


Mongo Express server listening at http://0.0.0.0:8081
Server is open to allow connections from anyone (0.0.0.0)

/node_modules/mongodb/lib/server.js:265
        process.nextTick(function() { throw err; })
                                      ^
MongoError: failed to connect to server [localhost:27017] on first connect
    at Pool.<anonymous> (/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)

**Comment by thedevtron** [comment]
Inside your mongo-express settings you need to find `ME_CONFIG_MONGODB_SERVER` and change the mongo part to your external ip. This is what I had to change for it to work with plesk
