### ISSUE TITLE
crash when waiting for mongodb during initialization

### ISSUE THREAD

**Issue by thomasd3** [mongo-express/mongo-express#436]
When running mongodb and mongo-express in the same docker-compose file, if mongodb takes time to initialize and is not accepting connections, mongo-express crashes directly.

In the log below, mongo started to accept connections about 12 seconds after this.
we can set mongodb as a dependency, but we can 't control how long it will take until mongodb is ready to accept a connection, especially if it has to do some cleanup.

So, we need a mechanism to retry connections

```
Oct 07 17:26:57 92.251.109.163 hd-mongo-express: Welcome to mongo-express 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express: ------------------------ 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express: Mongo Express server listening at http://0.0.0.0:8081 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express: Server is open to allow connections from anyone (0.0.0.0) 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express: basicAuth credentials are "admin:pass", it is recommended you change this in your config.js! 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express: /node_modules/mongodb/lib/server.js:265 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express:         process.nextTick(function() { throw err; }) 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express:                                       ^ 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express: MongoError: failed to connect to server [mongodb:27017] on first connect 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express:     at Pool.<anonymous> (/node_modules/mongodb-core/lib/topologies/server.js:326:35) 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express:     at emitOne (events.js:116:13) 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express:     at Pool.emit (events.js:211:7) 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express:     at Connection.<anonymous> (/node_modules/mongodb-core/lib/connection/pool.js:270:12) 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express:     at Object.onceWrapper (events.js:317:30) 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express:     at emitTwo (events.js:126:13) 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express:     at Connection.emit (events.js:214:7) 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express:     at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:175:49) 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express:     at Object.onceWrapper (events.js:315:30) 
Oct 07 17:26:57 92.251.109.163 hd-mongo-express:     at emitOne (events.js:116:13) 
```

**Comment by wulfsolter** [comment]
Try using https://github.com/vishnubob/wait-for-it as suggested by Docker on https://docs.docker.com/compose/startup-order/

**Comment by thomasd3** [comment]
Great, thanks!

**Comment by laurivosandi** [comment]
Not being able to connect to Mongo is IMHO transient issue and I think mongo-express should not crash because of that. The error should just bubble up in the UI as appropriate a'la HTTP 500 unable to connect to Mongo
