### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by interpegasus** [mongo-express/mongo-express#459]
Hi, When clicking on 'View' via the admin list of databases, it returns " 502 Bad Gateway
nginx/1.14.1". I would like to know how to fix the issue. Thank you

**Log** 
```
TypeError: Cannot read property 'toString' of undefined
    at /var/app/current/node_modules/mongo-express/lib/routes/database.js:40:49
    at handleCallback (/var/app/current/node_modules/mongo-express/node_modules/mongodb/lib/utils.js:95:56)
    at /var/app/current/node_modules/mongo-express/node_modules/mongodb/lib/db.js:313:5
    at /var/app/current/node_modules/mongo-express/node_modules/mongodb-core/lib/connection/pool.js:455:18
    at process._tickCallback (internal/process/next_tick.js:61:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! br@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the br@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

```

### mongo-express-config.js
```
'use strict';
const developmentMode = false;
var appData = require('./server');

var mongo = {
    // setting the connection string will only give access to that database
    // to see more databases you need to set mongodb.admin to true or add databases to the mongodb.auth list
    connectionString: appData.dbUrl,
};

module.exports = {
    mongodb: {
        // if a connection string options such as server/port/etc are ignored
        connectionString: mongo.connectionString || '',

        server: developmentMode === true ? 'localhost' : 'db.cluster-ctq4sqvyjuec.us-east-1.docdb.amazonaws.com',
        port: 27017,
        ssl: developmentMode === false,
        sslValidate: false,
        sslAllowInvalidHostnames: true,
        sslCA: ['./rds-combined-ca-bundle.pem'],
        autoReconnect: true,
        poolSize: 5,
        admin: true,

        auth: [
            {
                database: 'br_dev',
                username: 'myusername',
                password: 'mypassword',
            },
            {
                database: 'br_pro',
                username: 'myusername',
                password: 'mypassword',
            }
        ],
        adminUsername: 'myusername',
        adminPassword: 'mypassword',

        //whitelist: hide all databases except the ones in this list  (empty list for no whitelist)
        whitelist: [],

        //blacklist: hide databases listed in the blacklist (empty list for no blacklist)
        blacklist: [],
    },

    site: {
        // baseUrl: the URL that mongo express will be located at - Remember to add the forward slash at the start and end!
        baseUrl: process.env.ME_CONFIG_SITE_BASEURL || '/',
        cookieKeyName: 'mongo-express',
        cookieSecret: process.env.ME_CONFIG_SITE_COOKIESECRET || 'cookiesecret',
        host: process.env.VCAP_APP_HOST || 'localhost',
        port: process.env.VCAP_APP_PORT || 8081,
        requestSizeLimit: process.env.ME_CONFIG_REQUEST_SIZE || '50mb',
        sessionSecret: process.env.ME_CONFIG_SITE_SESSIONSECRET || 'sessionsecret',
        sslCert: process.env.ME_CONFIG_SITE_SSL_CRT_PATH || '',
        sslEnabled: process.env.ME_CONFIG_SITE_SSL_ENABLED || false,
        sslKey: process.env.ME_CONFIG_SITE_SSL_KEY_PATH || '',
    },

    //set useBasicAuth to true if you want to authenticate mongo-express loggins
    //if admin is false, the basicAuthInfo list below will be ignored
    //this will be true unless ME_CONFIG_BASICAUTH_USERNAME is set and is the empty string
    useBasicAuth: process.env.ME_CONFIG_BASICAUTH_USERNAME !== '',

    basicAuth: {
        username: 'admin',
        password: 'mypassword',
    },

    options: {
        // Display startup text on console
        console: true,

        //documentsPerPage: how many documents you want to see at once in collection view
        documentsPerPage: 30,

        //editorTheme: Name of the theme you want to use for displaying documents
        //See http://codemirror.net/demo/theme.html for all examples
        editorTheme: process.env.ME_CONFIG_OPTIONS_EDITORTHEME || 'rubyblue',

        // Maximum size of a single property & single row
        // Reduces the risk of sending a huge amount of data when viewing collections
        maxPropSize: (100 * 1000),  // default 100KB
        maxRowSize: (1000 * 1000),  // default 1MB

        //The options below aren't being used yet

        //cmdType: the type of command line you want mongo express to run
        //values: eval, subprocess
        //  eval - uses db.eval. commands block, so only use this if you have to
        //  subprocess - spawns a mongo command line as a subprocess and pipes output to mongo express
        cmdType: 'eval',

        //subprocessTimeout: number of seconds of non-interaction before a subprocess is shut down
        subprocessTimeout: 300,

        //readOnly: if readOnly is true, components of writing are not visible.
        readOnly: process.env.ME_CONFIG_OPTIONS_READONLY || false,

        //collapsibleJSON: if set to true, jsons will be displayed collapsible
        collapsibleJSON: true,

        //collapsibleJSONDefaultUnfold: if collapsibleJSON is set to `true`, this defines default level
        //  to which JSONs are displayed unfolded; use number or "all" to unfold all levels
        collapsibleJSONDefaultUnfold: 1,

        //gridFSEnabled: if gridFSEnabled is set to 'true', you will be able to manage uploaded files ( ak. grids, gridFS )
        gridFSEnabled: process.env.ME_CONFIG_SITE_GRIDFS_ENABLED || false,

        // logger: this object will be used to initialize router logger (morgan)
        logger: {},

        //confirmDelete: if confirmDelete is set to 'true', a modal for confirming deletion is displayed before deleting a document/collection
        confirmDelete: false,

        //noExport: if noExport is set to true, we won't show export buttons
        noExport: false,
    },

    // Specify the default keyname that should be picked from a document to display in collections list.
    // Keynames can be specified for every database and collection.
    // If no keyname is specified, it defaults to '_id', which is a mandatory field.
    // For Example :
    // defaultKeyNames{
    //   "world_db":{  //Database Name
    //     "continent":"cont_name", // collection:field
    //     "country":"country_name",
    //     "city":"name"
    //   }
    // }
    defaultKeyNames: {

    },
};

```

**Comment by interpegasus** [comment]
It looks like the issue might been caused on version 3.6
