### ISSUE TITLE
It attempts to connect to `mongo:27017` even with a different host on ME_CONFIG_MONGODB_URL

### ISSUE THREAD

**Issue by vboufleur** [mongo-express/mongo-express#461]
Hi all!

I configured mongo-express to connect to my mongoDB instance with this URL configured in `ME_CONFIG_MONGODB_URL`:
```
mongodb://***:***@ds223756.mlab.com:23756/****
```

But the container attempts to connect to the default `mongo` host still and fails everytime. These are the container logs:
```

Welcome to mongo-express,
,
------------------------,
Server is open to allow connections from anyone (0.0.0.0),
Mongo Express server listening at http://0.0.0.0:8081,
basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!,
/node_modules/mongodb/lib/server.js:265,
        process.nextTick(function() { throw err; }),
                                      ^,
MongoError: failed to connect to server [mongo:27017] on first connect,
    at Pool.<anonymous> (/node_modules/mongodb-core/lib/topologies/server.js:326:35),
    at Pool.emit (events.js:211:7),
    at emitOne (events.js:116:13),
    at Connection.<anonymous> (/node_modules/mongodb-core/lib/connection/pool.js:270:12),
    at Object.onceWrapper (events.js:317:30),
    at Connection.emit (events.js:214:7),
    at emitTwo (events.js:126:13),
    at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:175:49),
    at Object.onceWrapper (events.js:315:30)
```

Is this a bug? A misconfiguration of my part? Thanks in advance.

**Comment by klubi** [comment]
I ran into the same issue.

**Comment by AndresSomadossi** [comment]
The same problem here. I'm trying to connect to AWS DocumentDB. Any news about this?

**Comment by klubi** [comment]
I have a workaround for AWS DocumentDB - https://github.com/mongo-express/mongo-express/issues/484#issuecomment-515013150
It does not work with latest available docker image, which is few versions of mongo-express behind...

**Comment by vinogradovia** [comment]
I set env `ME_CONFIG_MONGODB_SERVER: ''` and this works 
```
Mongo Express server listening at http://0.0.0.0:8081
Server is open to allow connections from anyone (0.0.0.0)#033[39m
Database connected
Connected to dbname 
```
But in `/ docker-entrypoint.sh` the function` wait_tcp_port` is used without analysis env `ME_CONFIG_MONGODB_URL`. 

```
retrying to connect to :27017 (4/5)
Name does not resolve
/dev/tcp//27017: Invalid argument
Name does not resolve
/dev/tcp//27017: Invalid argument
 retrying to connect to :27017 (5/5)
Welcome to mongo-express
```
Any suggestions for a fix?

**Comment by Marcon** [comment]
So I got mongo-express running with using ME_CONFIG_MONGODB_URL, by downgrading container to 0.45 version. Everything above 0.45 refuses to use URL variable
My docker-compose looks like this:

```
services:
  mongo-express:
    image: mongo-express:0.45
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: ''
      ME_CONFIG_MONGODB_URL: 'mongodb://user:password@shards...'
```

**Comment by sapisuper** [comment]
@Marcon Thank dude, I tried using latest version and always failed when ME_CONFIG_MONGODB_SERVER : ''. nice info for specific version 👍

**Comment by VijayStroup** [comment]
Issue is still relevant with latest version as of now: 0.54

**Comment by sammed-ai** [comment]
How did you guys use the SSH connection to EC2 instance in the mongo-express config.json?
