### ISSUE TITLE
[bug] run in docker,master branch 675d3440229c560a38a7382df46d7a7574e0e8ec

### ISSUE THREAD

**Issue by kobeng** [mongo-express/mongo-express#544]
> mongo-express@0.53.0 start /app
> cross-env NODE_ENV=production node app

module.js:550
    throw err;
    ^

Error: Cannot find module 'mongodb-query-parser'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/app/lib/bson.js:3:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mongo-express@0.53.0 start: `cross-env NODE_ENV=production node app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mongo-express@0.53.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by dozoisch** [comment]
Hi, 

You need to install dependencies after cloning the repo. Master has more dependencies requirements than the latest release. Check the package.json on master
