### ISSUE TITLE
/docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument

### ISSUE THREAD

**Issue by lecorreyann** [mongo-express/mongo-express#563]
Hello, 

I have an error and I read about this in all web I think and I can't solve my problem. 

**My VPS** 
Configuration : PLESK Obsidian 18.0.25
OS : Ubuntu 18.04.4 LTS

**Expected**
The deal : I want to connect mongo-express with my mongo container to administrate mongo database. 

So I've installed Docker and with docker-hub Mongo and Mongo-Express

My mongo container name to mongo is "mongo" and my mongo-express container name is "mongo-express" 

**Mongo container**
manual mapping 2017 : 2017 
MONGO_INITDB_ROOT_USERNAME : root 
MONGO_INITDB_ROOT_PASSWORD: password 

**Mongo Express container**
manual mapping 8081:8081
ME_CONFIG_MONGODB_SERVER: mongo (name of my mongo container if I understood)
ME_CONFIG_BASICAUTH_USERNAME: root
ME_CONFIG_BASICAUTH_PASSWORD: password 
VCAP_APP_HOST: 0.0.0.0

**What mongo says ?** (started)

2020-04-06T18:59:49.467+0000 I  FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
2020-04-06T18:59:49.475+0000 I  SHARDING [LogicalSessionCacheRefresh] Marking collection config.system.sessions as collection version: <unsharded>
2020-04-06T18:59:49.476+0000 I  SHARDING [LogicalSessionCacheReap] Marking collection config.transactions as collection version: <unsharded>
2020-04-06T18:59:49.476+0000 I  NETWORK  [listener] Listening on /tmp/mongodb-27017.sock
2020-04-06T18:59:49.477+0000 I  NETWORK  [listener] **Listening on 0.0.0.0**
2020-04-06T18:59:49.477+0000 I  NETWORK  [listener] **waiting for connections on port 27017**
2020-04-06T18:59:50.005+0000 I  SHARDING [ftdc] Marking collection local.oplog.rs as collection version: <unsharded>

**What mongo express says ?** (started)

Waiting for mongo:27017...
Mon Apr  6 19:16:47 UTC 2020 retrying to connect to mongo:27017 (2/5)
Mon Apr  6 19:16:53 UTC 2020 retrying to connect to mongo:27017 (3/5)
Mon Apr  6 19:16:59 UTC 2020 retrying to connect to mongo:27017 (4/5)
Mon Apr  6 19:17:05 UTC 2020 retrying to connect to mongo:27017 (5/5)
Welcome to mongo-express
------------------------
Mongo Express server listening at http://0.0.0.0:8081
--
**/docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
[31mServer is open to allow connections from anyone (0.0.0.0)[39m**

/node_modules/mongodb/lib/server.js:265
        process.nextTick(function() { throw err; })
                                      ^
Error [MongoError]: failed to connect to server [mongo:27017] on first connect
    at Pool.<anonymous> (/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at Pool.emit (events.js:311:20)
    at Connection.<anonymous> (/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Object.onceWrapper (events.js:418:26)
    at Connection.emit (events.js:311:20)
    at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Object.onceWrapper (events.js:418:26)
    at Socket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3) {
  name: 'MongoError',
  message: 'failed to connect to server [mongo:27017] on first connect'
}

Any Idea ?

**Comment by garooo** [comment]
same issue

**Comment by mrt2410** [comment]
Hi @lecorreyann 

You wrote:
> My mongo container name to mongo is "mongo" and my mongo-express container name is "mongo-express"

This sound like you started containers individual without creating a docker network and put both of them in same network. This result that they will not communicate.

2nd, the MongoExpress environments:

```
ME_CONFIG_BASICAUTH_USERNAME: root
ME_CONFIG_BASICAUTH_PASSWORD: password
```

are related to browser Basic Auth credentials.

In your case, for mongo credentials, you need to use:

```
ME_CONFIG_MONGODB_ADMINUSERNAME: root
ME_CONFIG_MONGODB_ADMINPASSWORD: password
```

Please try.

**Comment by batressc** [comment]
Your issue is caused by a configuration set in the container's `/docker-entrypoint.sh` file, specifically in the following lines:

**Comment by kekius-maximus45** [comment]
@mongo-express Hi, I'd like to work on this issue if it's still available.

I have relevant experience with Node, Express, MongoDB, Docker. For "/docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument", I would first reproduce/verify the current behavior, make a focused implementation in mongo-express/mongo-express, and add or update tests around the changed path.

Please assign this to me if that approach sounds good.

**Comment by rtritto** [comment]
@Tejasmore45 hi, I assigned to you

**Comment by kekius-maximus45** [comment]
@rtritto check the PR
