### ISSUE TITLE
Persistent "Authentication Failed" 

### ISSUE THREAD

**Issue by brenojac** [mongo-express/mongo-express#579]
Hello my dear friends. 

I've been trying to setup a docker container with MongoExpress + MongoDB all week long. I really tried fixing it using all information available on google, but I believe it exausted the possibilities of something obvious I'm missing. Here's my docker-compose (I'm omitting whatever is not related to mongodb and mdb express):

`` mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=auth
    networks:
      - education-network
    volumes:
      - ./strapidb:/data/db
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    env_file: .env
    environment:
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_PORT=${ME_CONFIG_MONGODB_PORT}
    depends_on:
      - mongo
    links:
      - mongo
  networks:
      - education-network

networks:
  education-network:
    driver: bridge

``

Here's my .env file (it's ok about passwords, I'll change them later, just for the sake of debugging this issue):
``
DATABASE_CLIENT=mongo
DATABASE_NAME=strapi
DATABASE_HOST=mongodb
DATABASE_PORT=27017
DATABASE_USERNAME=strapi
DATABASE_PASSWORD=password
MONGO_INITDB_ROOT_USERNAME=admin
MONGO_INITDB_ROOT_PASSWORD=pass
ME_CONFIG_MONGODB_ADMINUSERNAME=admin
ME_CONFIG_MONGODB_ADMINPASSWORD=pass
ME_CONFIG_MONGODB_SERVER=mongodb
ME_CONFIG_BASICAUTH_USERNAME=admin
ME_CONFIG_BASICAUTH_PASSWORD=pass
ME_CONFIG_MONGODB_PORT=27017
``

It runs just fine: 

``
root@educationexperience:~/services/strapi# docker-compose up -d
Creating network "strapi_education-network" with driver "bridge"
Creating strapi                 ... done
Creating mongodb ... done
Creating strapi_mongo-express_1 ... done
``

It is hosted at https://mdb.projetoalex.cc. It's aparrently ok but no database is possible to create or edit, listing... 

Here is the docker logs output: 

``
mongo-express_1  | Welcome to mongo-express
mongo-express_1  | ------------------------
mongo-express_1  | 
mongo-express_1  | 
mongo-express_1  | Mongo Express server listening at http://0.0.0.0:8081
mongo-express_1  | Server is open to allow connections from anyone (0.0.0.0)
mongo-express_1  | basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
mongodb          | 2020-06-25T14:18:14.930+0000 I  NETWORK  [listener] connection accepted from 172.30.0.4:39680 #2 (1 connection now open)
mongodb          | 2020-06-25T14:18:14.941+0000 I  NETWORK  [conn2] received client metadata from 172.30.0.4:39680 conn2: { driver: { name: "nodejs", version: "2.2.24" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-101-generic" }, platform: "Node.js v12.18.1, LE, mongodb-core: 2.1.8" }
mongo-express_1  | Database connected
mongodb          | 2020-06-25T14:18:14.951+0000 I  SHARDING [conn2] Marking collection admin.system.users as collection version: <unsharded>
mongodb          | 2020-06-25T14:18:14.952+0000 I  ACCESS   [conn2] SASL SCRAM-SHA-1 authentication failed for admin on admin from client 172.30.0.4:39680 ; UserNotFound: Could not find user "admin" for db "admin"
mongo-express_1  | Error [MongoError]: Authentication failed.
mongo-express_1  |     at Function.MongoError.create (/node_modules/mongodb-core/lib/error.js:31:11)
mongo-express_1  |     at /node_modules/mongodb-core/lib/connection/pool.js:483:72
mongo-express_1  |     at authenticateStragglers (/node_modules/mongodb-core/lib/connection/pool.js:429:16)
mongo-express_1  |     at Connection.messageHandler (/node_modules/mongodb-core/lib/connection/pool.js:463:5)
mongo-express_1  |     at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:319:22)
mongo-express_1  |     at Socket.emit (events.js:315:20)
mongo-express_1  |     at addChunk (_stream_readable.js:295:12)
mongo-express_1  |     at readableAddChunk (_stream_readable.js:271:9)
mongo-express_1  |     at Socket.Readable.push (_stream_readable.js:212:10)
mongo-express_1  |     at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
mongo-express_1  |   ok: 0,
mongo-express_1  |   errmsg: 'Authentication failed.',
mongo-express_1  |   code: 18,
mongo-express_1  |   codeName: 'AuthenticationFailed'
mongo-express_1  | }
mongo-express_1  | Admin Database connected
mongo-express_1  | unable to list databases
mongo-express_1  | Error [MongoError]: command listDatabases requires authentication
mongo-express_1  |     at Function.MongoError.create (/node_modules/mongodb-core/lib/error.js:31:11)
mongo-express_1  |     at /node_modules/mongodb-core/lib/connection/pool.js:483:72
mongo-express_1  |     at authenticateStragglers (/node_modules/mongodb-core/lib/connection/pool.js:429:16)
mongo-express_1  |     at Connection.messageHandler (/node_modules/mongodb-core/lib/connection/pool.js:463:5)
mongo-express_1  |     at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:319:22)
mongo-express_1  |     at Socket.emit (events.js:315:20)
mongo-express_1  |     at addChunk (_stream_readable.js:295:12)
mongo-express_1  |     at readableAddChunk (_stream_readable.js:271:9)
mongo-express_1  |     at Socket.Readable.push (_stream_readable.js:212:10)
mongo-express_1  |     at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
mongo-express_1  |   ok: 0,
mongo-express_1  |   errmsg: 'command listDatabases requires authentication',
mongo-express_1  |   code: 13,
mongo-express_1  |   codeName: 'Unauthorized'
mongo-express_1  | }

``

     Sorry for this long post. But I really tried all options and I'm stuck with this issue. Hoping you guys can help me debug and solve it. 

Thanks in advance.

- Breno

**Comment by Anzze** [comment]
Any luck with this one? I'm experiencing similar issue when running inside Kubernetes.

**Comment by deba10106** [comment]
Me too!

**Comment by Braedencraig** [comment]
Also having this issue! My credentials are correct!! What the HECK!

**Comment by deba10106** [comment]
Hey, I know why....you need to do this: instead of echo password | base64,
do echo -n password | base64 and of course same for username.

Just try!

**Comment by fpause** [comment]
I'm facing the same issue (using MongoDB Community Kubernetes Operator)

@deba10106 Where do you have to use the base64 encoding (when setting the password with MongoDB or just as a value for ME_CONFIG_MONGODB_ADMINPASSWORD)?

**Comment by Braedencraig** [comment]
@fpause are you using docker? If so, I might be able to help with your issue.

**Comment by moyee** [comment]
Me too!

**Comment by moyee** [comment]
> Hello my dear friends.
> 
> I've been trying to setup a docker container with MongoExpress + MongoDB all week long. I really tried fixing it using all information available on google, but I believe it exausted the possibilities of something obvious I'm missing. Here's my docker-compose (I'm omitting whatever is not related to mongodb and mdb express):
> 
> ```
> mongo:
>     image: mongo
>     container_name: mongodb
>     restart: unless-stopped
>     env_file: .env
>     environment:
>       - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
>       - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
>       - MONGO_INITDB_DATABASE=auth
>     networks:
>       - education-network
>     volumes:
>       - ./strapidb:/data/db
>     ports:
>       - "27017:27017"
> 
>   mongo-express:
>     image: mongo-express
>     ports:
>       - 8081:8081
>     env_file: .env
>     environment:
>       - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
>       - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
>       - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
>       - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
>       - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
>       - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
>       - ME_CONFIG_MONGODB_PORT=${ME_CONFIG_MONGODB_PORT}
>     depends_on:
>       - mongo
>     links:
>       - mongo
>   networks:
>       - education-network
> 
> networks:
>   education-network:
>     driver: bridge
> ```
> 
> Here's my .env file (it's ok about passwords, I'll change them later, just for the sake of debugging this issue):
> 
> ```
> DATABASE_CLIENT=mongo
> DATABASE_NAME=strapi
> DATABASE_HOST=mongodb
> DATABASE_PORT=27017
> DATABASE_USERNAME=strapi
> DATABASE_PASSWORD=password
> MONGO_INITDB_ROOT_USERNAME=admin
> MONGO_INITDB_ROOT_PASSWORD=pass
> ME_CONFIG_MONGODB_ADMINUSERNAME=admin
> ME_CONFIG_MONGODB_ADMINPASSWORD=pass
> ME_CONFIG_MONGODB_SERVER=mongodb
> ME_CONFIG_BASICAUTH_USERNAME=admin
> ME_CONFIG_BASICAUTH_PASSWORD=pass
> ME_CONFIG_MONGODB_PORT=27017
> ```
> 
> It runs just fine:
> 
> ```
> root@educationexperience:~/services/strapi# docker-compose up -d
> Creating network "strapi_education-network" with driver "bridge"
> Creating strapi                 ... done
> Creating mongodb ... done
> Creating strapi_mongo-express_1 ... done
> ```
> 
> It is hosted at https://mdb.projetoalex.cc. It's aparrently ok but no database is possible to create or edit, listing...
> 
> Here is the docker logs output:
> 
> ```
> 
> mongo-express_1  | Welcome to mongo-express
> mongo-express_1  | ------------------------
> mongo-express_1  | 
> mongo-express_1  | 
> mongo-express_1  | Mongo Express server listening at http://0.0.0.0:8081
> mongo-express_1  | Server is open to allow connections from anyone (0.0.0.0)
> mongo-express_1  | basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
> mongodb          | 2020-06-25T14:18:14.930+0000 I  NETWORK  [listener] connection accepted from 172.30.0.4:39680 #2 (1 connection now open)
> mongodb          | 2020-06-25T14:18:14.941+0000 I  NETWORK  [conn2] received client metadata from 172.30.0.4:39680 conn2: { driver: { name: "nodejs", version: "2.2.24" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "4.15.0-101-generic" }, platform: "Node.js v12.18.1, LE, mongodb-core: 2.1.8" }
> mongo-express_1  | Database connected
> mongodb          | 2020-06-25T14:18:14.951+0000 I  SHARDING [conn2] Marking collection admin.system.users as collection version: <unsharded>
> mongodb          | 2020-06-25T14:18:14.952+0000 I  ACCESS   [conn2] SASL SCRAM-SHA-1 authentication failed for admin on admin from client 172.30.0.4:39680 ; UserNotFound: Could not find user "admin" for db "admin"
> mongo-express_1  | Error [MongoError]: Authentication failed.
> mongo-express_1  |     at Function.MongoError.create (/node_modules/mongodb-core/lib/error.js:31:11)
> mongo-express_1  |     at /node_modules/mongodb-core/lib/connection/pool.js:483:72
> mongo-express_1  |     at authenticateStragglers (/node_modules/mongodb-core/lib/connection/pool.js:429:16)
> mongo-express_1  |     at Connection.messageHandler (/node_modules/mongodb-core/lib/connection/pool.js:463:5)
> mongo-express_1  |     at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:319:22)
> mongo-express_1  |     at Socket.emit (events.js:315:20)
> mongo-express_1  |     at addChunk (_stream_readable.js:295:12)
> mongo-express_1  |     at readableAddChunk (_stream_readable.js:271:9)
> mongo-express_1  |     at Socket.Readable.push (_stream_readable.js:212:10)
> mongo-express_1  |     at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
> mongo-express_1  |   ok: 0,
> mongo-express_1  |   errmsg: 'Authentication failed.',
> mongo-express_1  |   code: 18,
> mongo-express_1  |   codeName: 'AuthenticationFailed'
> mongo-express_1  | }
> mongo-express_1  | Admin Database connected
> mongo-express_1  | unable to list databases
> mongo-express_1  | Error [MongoError]: command listDatabases requires authentication
> mongo-express_1  |     at Function.MongoError.create (/node_modules/mongodb-core/lib/error.js:31:11)
> mongo-express_1  |     at /node_modules/mongodb-core/lib/connection/pool.js:483:72
> mongo-express_1  |     at authenticateStragglers (/node_modules/mongodb-core/lib/connection/pool.js:429:16)
> mongo-express_1  |     at Connection.messageHandler (/node_modules/mongodb-core/lib/connection/pool.js:463:5)
> mongo-express_1  |     at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:319:22)
> mongo-express_1  |     at Socket.emit (events.js:315:20)
> mongo-express_1  |     at addChunk (_stream_readable.js:295:12)
> mongo-express_1  |     at readableAddChunk (_stream_readable.js:271:9)
> mongo-express_1  |     at Socket.Readable.push (_stream_readable.js:212:10)
> mongo-express_1  |     at TCP.onStreamRead (internal/stream_base_commons.js:186:23) {
> mongo-express_1  |   ok: 0,
> mongo-express_1  |   errmsg: 'command listDatabases requires authentication',
> mongo-express_1  |   code: 13,
> mongo-express_1  |   codeName: 'Unauthorized'
> mongo-express_1  | }
> ```
> 
> Sorry for this long post. But I really tried all options and I'm stuck with this issue. Hoping you guys can help me debug and solve it.
> 
> Thanks in advance.
> 
> * Breno

    environment:
      ME_CONFIG_MONGODB_SERVER: serip
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_BASICAUTH_USERNAME: username
      ME_CONFIG_BASICAUTH_PASSWORD: password
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongouser
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongpasswd

**Comment by Ryonez** [comment]
> 
> 
> @fpause The solve for me was setting docker to a clean slate, and trying to authenticate again.
> 
> delete node_modules and package-lock, docker volume prune, docker rmi $(docker images -a -q), docker system prune

I'm setting up just after cleaning docker when I found this issue. It's present and making mongo-express completely unusable.

**Comment by StMarian** [comment]
@fpause, did you find a solution? I am also having the same issue with MongoDB Community Kubernetes Operator

**Comment by StMarian** [comment]
Looks like it got fixed in [v1.0.0-alpha.1](https://github.com/mongo-express/mongo-express/tree/v1.0.0-alpha.1)

**Comment by ThasneemGafoor93** [comment]
Hi everyone, wondering if there's a clear fix to this issue as I am facing the same/similar.

Trying to create a small simple k8s cluster using minikube, where I have a mongoDB pod and a mongo-express pod. 

I've created relevant secret, configmap and service yaml files.

I build the deployment files by doing k apply -f mongodb-deployment.yaml and k apply -f mongo-express.yaml

My mongoDB pod is spinning up the pod fine - I check the logs for these. But my mongo-express pod results in 

`Mongo Express server listening at http://0.0.0.0:8081
Server is open to allow connections from anyone (0.0.0.0)
Database connected
Admin Database connected
unable to list databases
Error [MongoError]: command listDatabases requires authentication
    at Function.MongoError.create (/node_modules/mongodb-core/lib/error.js:31:11)
    at /node_modules/mongodb-core/lib/connection/pool.js:483:72
    at authenticateStragglers (/node_modules/mongodb-core/lib/connection/pool.js:429:16)
    at Connection.messageHandler (/node_modules/mongodb-core/lib/connection/pool.js:463:5)
    at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:319:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  ok: 0,
  errmsg: 'command listDatabases requires authentication',
  code: 13,
  codeName: 'Unauthorized'
}`

Really cant see a solution anywhere... trying to find the fix referenced in @StMarian 's comment above

Any help would be appreciated

**Comment by tomislater** [comment]
@StMarian I had to add support for `SCRAM-SHA-1` in MongoDB Community Kubernetes Operator. By default there is a support only for the new one: `SCRAM-SHA-256`.

```
...
spec:
  security:
    authentication:
      modes: ["SCRAM", "SCRAM-SHA-1"]
...
```

After that, `mongo-express` (`0.54.0`) connected to my mongo (`4.2`).

https://www.mongodb.com/docs/manual/core/security-scram/

Maybe, `mongo-express` uses old library where only `SCRAM-SHA-1` mechanism is supported?

I saw some bumps of packages in `1.0.0`, so maybe that's why it works on this tag.

**Comment by Genialngash** [comment]
anyone who has found a solution?
I am facing a similar issue

**Comment by deba10106** [comment]
Hey, I know why....you need to do this: instead of echo password | base64,
do echo -n password | base64 and of course same for username.

Just try!

**Comment by apeixinho** [comment]
Well ... from my struggle with this .. I can share that not quoting "true" "false" values does lead to inconsistent behaviour
I have a very similar docker compose and these 2 expressions behave differently.
```
ME_CONFIG_MONGODB_ENABLE_ADMIN=true
ME_CONFIG_MONGODB_ENABLE_ADMIN="true"
```

**Comment by GerritErpenstein** [comment]
> @StMarian I had to add support for `SCRAM-SHA-1` in MongoDB Community Kubernetes Operator. By default there is a support only for the new one: `SCRAM-SHA-256`.
> 
> ```
> ...
> spec:
>   security:
>     authentication:
>       modes: ["SCRAM", "SCRAM-SHA-1"]
> ...
> ```
> 
> After that, `mongo-express` (`0.54.0`) connected to my mongo (`4.2`).
> 
> https://www.mongodb.com/docs/manual/core/security-scram/
> 
> Maybe, `mongo-express` uses old library where only `SCRAM-SHA-1` mechanism is supported?
> 
> I saw some bumps of packages in `1.0.0`, so maybe that's why it works on this tag.

I can confirm that this is the solution when MongoDB Community Kubernetes operator is used. It took me half a day to find the comment and thus the solution. Thanks a lot! 😊

I am using version `1.0.2-rc` of mongo-express. So the problem with the unsupported authentenication mechanism does not seem to be solved by the mentioned upgrade of the dependencies.

**Comment by jesraygarciano** [comment]
I have the same issue.

**Comment by kmsky** [comment]
For people who still have this problem, there is solution for docker-compose:

```
volumes:
  netfishing_local_mongo_data: {}

services:
  mongo:
    image: mongo:7
    container_name: netfishing_local_mongo
    volumes:
      - netfishing_local_mongo_data:/data/db
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express:1
    container_name: netfishing_local_mongo_express
    depends_on:
      - mongo
    ports:
      - '8081:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
```

Good luck!

**Comment by skaarlcooper** [comment]
I'm using docker to install mongodb service in my Go project and have the same issue here. 
`panic: connection() error occurred during connection handshake: auth error: unable to authenticate using mechanism "SCRAM-SHA-256": (AuthenticationFailed) Authentication failed.`
So I do the following below to fix it:

1. Upgrading to SCRAM-SHA-256: ([mongodb](https://www.mongodb.com/community/forums/t/upgrading-from-scram-sha-1-to-scram-sha-256/204431/4)
`use admin
db.runCommand({'updateUser':'user0',pwd:passwordPrompt(), mechanisms:['SCRAM-SHA-256']})`
Btw, if you've not created user yet, you could created one with:
`db.createUser({user:"root",pwd:"yourPasword",roles:[{role:"rootAdminAnyDatabase",db:"admin"}, "readWriteAnyDatabase"]})`

2. As @kmsky said, I update port from 6000 to 27017, and it runs fine.
Here my `docker-compose.yml`:
`
version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - ./app.env

    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
`
and `app.env`:
`
PORT=8000

MONGO_INITDB_ROOT_USERNAME=root
MONGO_INITDB_ROOT_PASSWORD=yourPassword
MONGODB_LOCAL_URI=mongodb://root:yourPassword@localhost:27017

`
