### ISSUE TITLE
Cannot run mongo-express with inline params

### ISSUE THREAD

**Issue by scorpioRED** [mongo-express/mongo-express#596]
I have installed mongo-express globally and now try to run with params like:

`mongo-express -u myMongoUsername -p myMongoPassword -d database -H remoteHostIp -P mongoDefaultPort`

And  then I got :

`No custom config.js found, loading config.default.js
Welcome to mongo-express
------------------------

/Users/scorpio/.nvm/versions/node/v10.10.0/lib/node_modules/mongo-express/app.js:78
    config.mongodb.auth[0] = user;
                           ^

TypeError: Cannot set property '0' of undefined
    at Object.<anonymous> (/Users/scorpio/.nvm/versions/node/v10.10.0/lib/node_modules/mongo-express/app.js:78:28)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:279:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:696:3)`

How can I fix it?

**Comment by dusht0814** [comment]
I'll fix the error soon meanwhile, try using it with : 
mongo-express --url mongodb://myMongoUsername:myMongoPassword@remoteHostIp:mongoDefaultPort/database

**Comment by rtritto** [comment]
Fixed #602
