### ISSUE TITLE
ME_CONFIG_MONGODB_URL ignored

### ISSUE THREAD

**Issue by p-mongo** [mongo-express/mongo-express#617]
When I specify ME_CONFIG_MONGODB_URL in  docker  run, I expect mongo-express to use the specified URI, but it does not:

```
serene% docker run -it --rm -p 8081:8081 --env ME_CONFIG_MONGODB_URL=mongodb://serene:14400 mongo-express
Waiting for mongo:27017...
/docker-entrypoint.sh: line 14: mongo: Name does not resolve
/docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
Mon Oct 12 03:47:39 UTC 2020 retrying to connect to mongo:27017 (2/5)
/docker-entrypoint.sh: line 14: mongo: Name does not resolve
/docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
Mon Oct 12 03:47:40 UTC 2020 retrying to connect to mongo:27017 (3/5)
/docker-entrypoint.sh: line 14: mongo: Name does not resolve
/docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
Mon Oct 12 03:47:41 UTC 2020 retrying to connect to mongo:27017 (4/5)
/docker-entrypoint.sh: line 14: mongo: Name does not resolve
/docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
Mon Oct 12 03:47:42 UTC 2020 retrying to connect to mongo:27017 (5/5)
/docker-entrypoint.sh: line 14: mongo: Name does not resolve
/docker-entrypoint.sh: line 14: /dev/tcp/mongo/27017: Invalid argument
Welcome to mongo-express
------------------------


Mongo Express server listening at http://0.0.0.0:8081
Server is open to allow connections from anyone (0.0.0.0)
basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!

/node_modules/mongodb/lib/server.js:265
        process.nextTick(function() { throw err; })
                                      ^
Error [MongoError]: failed to connect to server [mongo:27017] on first connect
    at Pool.<anonymous> (/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at Pool.emit (events.js:314:20)
    at Connection.<anonymous> (/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Object.onceWrapper (events.js:421:26)
    at Connection.emit (events.js:314:20)
    at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
```

I tried setting ME_CONFIG_MONGODB_SERVER explicitly to an empty string but this doesn't work either:

```
serene% docker run -it --rm -p 8081:8081 --env ME_CONFIG_MONGODB_URL=mongodb://serene:14400 -e ME_CONFIG_MONGODB_SERVER= mongo-express
Waiting for :27017...
/docker-entrypoint.sh: line 14: : Name does not resolve
/docker-entrypoint.sh: line 14: /dev/tcp//27017: Invalid argument
Mon Oct 12 03:48:55 UTC 2020 retrying to connect to :27017 (2/5)
/docker-entrypoint.sh: line 14: : Name does not resolve
/docker-entrypoint.sh: line 14: /dev/tcp//27017: Invalid argument
Mon Oct 12 03:48:56 UTC 2020 retrying to connect to :27017 (3/5)
/docker-entrypoint.sh: line 14: : Name does not resolve
/docker-entrypoint.sh: line 14: /dev/tcp//27017: Invalid argument
Mon Oct 12 03:48:57 UTC 2020 retrying to connect to :27017 (4/5)
/docker-entrypoint.sh: line 14: : Name does not resolve
/docker-entrypoint.sh: line 14: /dev/tcp//27017: Invalid argument
Mon Oct 12 03:48:58 UTC 2020 retrying to connect to :27017 (5/5)
/docker-entrypoint.sh: line 14: : Name does not resolve
/docker-entrypoint.sh: line 14: /dev/tcp//27017: Invalid argument
Welcome to mongo-express
------------------------


Mongo Express server listening at http://0.0.0.0:8081
Server is open to allow connections from anyone (0.0.0.0)
basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!

/node_modules/mongodb/lib/mongo_client.js:336
          throw err
          ^
Error [MongoError]: failed to connect to server [serene:14400] on first connect
    at Pool.<anonymous> (/node_modules/mongodb-core/lib/topologies/server.js:326:35)
    at Pool.emit (events.js:314:20)
    at Connection.<anonymous> (/node_modules/mongodb-core/lib/connection/pool.js:270:12)
    at Object.onceWrapper (events.js:421:26)
    at Connection.emit (events.js:314:20)
    at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:175:49)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
```

**Comment by dozoisch** [comment]
probably fixed here https://github.com/mongo-express/mongo-express/pull/615

**Comment by p-mongo** [comment]
https://github.com/mongo-express/mongo-express/pull/615 seems to do with query execution, this issue as far as I can tell is with m-e configuration processing and I don't think it has anything to do with the driver at all.

**Comment by dozoisch** [comment]
@p-mongo sorry meant https://github.com/mongo-express/mongo-express/pull/614/files

**Comment by dozoisch** [comment]
Anyway I'll check the config, I'd like to simplify all theoptions and get rid of methods other than the URL one

**Comment by p-mongo** [comment]
That seems like it could be the fix although I am not 100% confident given the diff.

**Comment by hackerunet** [comment]
if I use a custom dockerfile with mongo-express build from source how can I pass the arguments to app.js file using RUN directive?
I have tried RUN nohup node node_modules/mongo-express/app.js but seems to not accept any parameters so if I pass from docker run the env varibles the app.js script never get the values and an error ocurr due to failed attempt to connect to undefined:27017

**Comment by diberry** [comment]
This isn't fixed yet - seems like a simple fix to the dockerfile to access the connection string would fix it.

**Comment by PythxnBite** [comment]
The issue still persists. I really need this to work for my college project so might fix it by myself and post a pull request if i can get it to work. The issue for me seems to be that not only does docker not use the url given, but it also doesn't accept the new DNS based url structure (url with +srv in protocol section). I tried to edit the connection code and even though the node.js driver is 3.6+ in package.json, error is thrown by the driver for some reason.
