### ISSUE TITLE
Can't run in command line 

### ISSUE THREAD

**Issue by JasonXiang2014** [mongo-express/mongo-express#623]
when i use below command:
 mongo-express -u user -p password -d database

```
No custom config.js found, loading config.default.js
Welcome to mongo-express
------------------------

/Users/apple/.nvm/versions/node/v12.18.3/lib/node_modules/mongo-express/app.js:78
    config.mongodb.auth[0] = user;
                           ^
TypeError: Cannot set property '0' of undefined
    at Object.<anonymous> (/Users/apple/.nvm/versions/node/v12.18.3/lib/node_modules/mongo-express/app.js:78:28)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```
when I install mongo-express globally, the outputs are here:

```
npm WARN deprecated express-fileupload@0.4.0: Please upgrade express-fileupload to version 1.1.8+ due to a security vulnerability with the parseNested option
/Users/apple/.nvm/versions/node/v12.18.3/bin/mongo-express -> /Users/apple/.nvm/versions/node/v12.18.3/lib/node_modules/mongo-express/app.js

> mongo-express@1.0.0-alpha.1 postinstall /Users/apple/.nvm/versions/node/v12.18.3/lib/node_modules/mongo-express
> patch-package

patch-package 6.2.2
Applying patches...

Warning: patch-package detected a patch file version mismatch

  Don't worry! This is probably fine. The patch was still applied
  successfully. Here's the deets:

  Patch file created for

    mongodb-query-parser@2.0.2

  applied to

    mongodb-query-parser@2.1.2

  At path

    node_modules/mongodb-query-parser

  This warning is just to give you a heads-up. There is a small chance of
  breakage even though the patch was applied successfully. Make sure the package
  still behaves like you expect (you wrote tests, right?) and then run

    patch-package mongodb-query-parser

  to update the version in the patch file name and make this warning go away.

npm WARN notsup Unsupported engine for got@5.7.1: wanted: {"node":">=0.10.0 <7"} (current: {"node":"12.18.3","npm":"6.14.6"})
npm WARN notsup Not compatible with your version of node/npm: got@5.7.1

+ mongo-express@1.0.0-alpha.1
```
Does mongo-express only support  below node 7 ?

**Comment by JasonXiang2014** [comment]
I read the source code，and find I made a mistake.
Here is my solution:

1  Copy YOUR_PATH/node_modules/mongo-express/config.default.js into a new file called YOUR_PATH/node_modules/mongo-express/config.js.
2  edit config.js
```
mongodb: {
    ...
    auth: [], // add this one
  },

```
3  run mongo-express -u admin -p pass -d database
