### ISSUE TITLE
npm run test fails at router

### ISSUE THREAD

**Issue by Kazuto** [mongo-express/mongo-express#634]
Hey guys,

I was trying to create a pull request but I can't commit the changes to my fork because the tests keep failing.

Is there anything I have to do to run the tests successfully?
MongoDB is running in a docker container and accessible on localhost:27017, checked with Robo T3.
I've even added a `mongo-express-test-db.test/items` but I just can't get it to work.

```
30 passing (104ms)
  8 failing

  1) Router collection
       "before all" hook for "GET /db/<dbName>/<collection> should return html":
     MongoError: command insert requires authentication
      at Connection.<anonymous> (node_modules/mongodb/lib/core/connection/pool.js:451:61)
      at processMessage (node_modules/mongodb/lib/core/connection/connection.js:452:10)
      at Socket.<anonymous> (node_modules/mongodb/lib/core/connection/connection.js:621:15)
      at addChunk (_stream_readable.js:309:12)
      at readableAddChunk (_stream_readable.js:284:9)
      at Socket.Readable.push (_stream_readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)

  2) Router collection
       "after all" hook for "GET /db/<dbName>/updateCollections/<collection> should updateCollections":
     TypeError: close is not a function
      at Context.<anonymous> (test/lib/routers/collectionSpec.js:47:5)
      at processImmediate (internal/timers.js:461:21)

  3) Router database
       "before all" hook for "GET /db/<dbName> should return html":
     Uncaught TypeError: Cannot read property 'db' of undefined
      at /Users/kaihillemacher/dev/private/mongo-express/test/testMongoUtils.js:35:18
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Function.Promise.fromNode.Promise.fromCallback (node_modules/bluebird/js/release/promise.js:209:30)
      at exports.asPromise (test/testUtils.js:6:19)
      at Object.exports.dropTestCollection (test/testMongoUtils.js:34:42)
      at Object.exports.cleanAndCloseDb (test/testMongoUtils.js:43:47)
      at Context.<anonymous> (test/lib/routers/collectionSpec.js:46:16)
      at processImmediate (internal/timers.js:461:21)

  4) Router database
       "after all" hook for "DEL /<dbName> should delete the db":
     TypeError: close is not a function
      at Context.<anonymous> (test/lib/routers/databaseSpec.js:37:5)
      at processImmediate (internal/timers.js:461:21)

  5) Router document
       "before all" hook for "GET /db/<dbName>/<collection>/<document> should return html":
     Uncaught TypeError: Cannot read property 'db' of undefined
      at /Users/kaihillemacher/dev/private/mongo-express/test/testMongoUtils.js:35:18
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Function.Promise.fromNode.Promise.fromCallback (node_modules/bluebird/js/release/promise.js:209:30)
      at exports.asPromise (test/testUtils.js:6:19)
      at Object.exports.dropTestCollection (test/testMongoUtils.js:34:42)
      at Object.exports.cleanAndCloseDb (test/testMongoUtils.js:43:47)
      at Context.<anonymous> (test/lib/routers/databaseSpec.js:36:16)
      at processImmediate (internal/timers.js:461:21)

  6) Router document
       "after all" hook for "PUT /db/<dbName>/<collection>/<document> should update the document":
     TypeError: close is not a function
      at Context.<anonymous> (test/lib/routers/documentSpec.js:40:5)
      at processImmediate (internal/timers.js:461:21)

  7) Router index
       "before all" hook for "GET / should return html":
     Uncaught TypeError: Cannot read property 'db' of undefined
      at /Users/kaihillemacher/dev/private/mongo-express/test/testMongoUtils.js:35:18
      at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at Function.Promise.fromNode.Promise.fromCallback (node_modules/bluebird/js/release/promise.js:209:30)
      at exports.asPromise (test/testUtils.js:6:19)
      at Object.exports.dropTestCollection (test/testMongoUtils.js:34:42)
      at Object.exports.cleanAndCloseDb (test/testMongoUtils.js:43:47)
      at Context.<anonymous> (test/lib/routers/documentSpec.js:39:16)
      at processImmediate (internal/timers.js:461:21)

  8) Router index
       "after all" hook for "GET / should return html":
     TypeError: close is not a function
      at Context.<anonymous> (test/lib/routers/indexSpec.js:32:5)
      at processImmediate (internal/timers.js:461:21)
```

**Comment by dozoisch** [comment]
>  MongoError: command insert requires authentication

Looks like your test database requires a username password, is that possible?

**Comment by Kazuto** [comment]
Thanks for your reply :)

I have no idea where to set this. The readme lacks how to set up for testing completely.

That's my mongo struct `config.js`
```
let mongo = {
  // Setting the connection string will only give access to that database
  // to see more databases you need to set mongodb.admin to true or add databases to the mongodb.auth list
  connectionString: process.env.ME_CONFIG_MONGODB_SERVER ? '' : process.env.ME_CONFIG_MONGODB_URL,
  host: '127.0.0.1',
  port: '27017',
  dbName: '',
  username: 'admin',
  password: 'password',
};
```

that's `testMongoConfig.js`
```
module.exports = {
  host: 'localhost',
  port: 27017,
  dbName: 'mongo-express-test-db',
  makeConnectionUrl: () => {
    const m = module.exports;
    return `mongodb://${m.host}:${m.port}/${m.dbName}`;
  },
};
```

**Comment by dozoisch** [comment]
Did you add them to the makeCOnnectionUrl (just making sure)? Because I think that's what gets used to connect. 

```
module.exports = {
  host: 'localhost',
  port: 27017,
  dbName: 'mongo-express-test-db',
  username: 'admin',
  password: 'password',
  makeConnectionUrl: () => {
    const m = module.exports;
    return `mongodb://${m.username}:${m.password}@${m.host}:${m.port}/${m.dbName}`;
  },
};
```

This code is very very old 😂 it could definitely get some love for testing and setup.

**Comment by Kazuto** [comment]
No, I didn't 😅

Now I'm getting the following error

```
1) Router collection
       "before all" hook for "GET /db/<dbName>/<collection> should return html":
     failed to connect to server [127.0.0.1:27017] on first connect [MongoError: Authentication failed.
    at Connection.messageHandler (/Users/kaihillemacher/dev/private/mongo-express/node_modules/mongodb/lib/core/connection/connection.js:360:19)
    at Connection.emit (events.js:315:20)
    at processMessage (/Users/kaihillemacher/dev/private/mongo-express/node_modules/mongodb/lib/core/connection/connection.js:452:10)
    at Socket.<anonymous> (/Users/kaihillemacher/dev/private/mongo-express/node_modules/mongodb/lib/core/connection/connection.js:621:15)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:284:9)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  ok: 0,
  code: 18,
  codeName: 'AuthenticationFailed'
}]
```

**Comment by Kazuto** [comment]
I've got it. The database itself was lacking the user with corresponding roles.

Didn't knew that.
