### ISSUE TITLE
GridFS Bucket type error mongo.connections[req.dbName].collection is not a function

### ISSUE THREAD

**Issue by mvitanov** [mongo-express/mongo-express#735]
Hey,

I have set up mongo-express in my project and I found a problem with using the GridFS Buckets. They are correctly recognized and loaded in the GUI, but when you click on any of them to view them, the following error is returned:

```
TypeError: mongo.connections[req.dbName].collection is not a function 
    at /node_modules/mongo-express/lib/router.js:222:35
    at paramCallback (/node_modules/express/lib/router/index.js:404:7)
    at param (/node_modules/express/lib/router/index.js:384:5)
    at paramCallback (/node_modules/express/lib/router/index.js:401:21)
    at /node_modules/mongo-express/lib/router.js:114:5
    at paramCallback (/node_modules/express/lib/router/index.js:404:7)
    at param (/node_modules/express/lib/router/index.js:384:5)
    at Function.process_params (/node_modules/express/lib/router/index.js:410:3)
    at next (/node_modules/express/lib/router/index.js:275:10)
    at next (/node_modules/express/lib/router/route.js:127:14)
    at /node_modules/mongo-express/lib/router.js:96:7
    at tryCatcher (/node_modules/mongo-express/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/node_modules/mongo-express/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/node_modules/mongo-express/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/node_modules/mongo-express/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/node_modules/mongo-express/node_modules/bluebird/js/release/promise.js:729:18)
```

I tried it both with a local mongo server and a remote one (MongoDB Atlas) - both resulting in the same issue. The rest of the mongo-express functionality works as expected.

Has someone had that error as well and do you know some workaround or a fix?

Thank you in advance for the support and thanks for this great tool to all the developers!

**Comment by tvandinther** [comment]
I am experiencing the same issue using the docker image.
