### ISSUE TITLE
[errlog] docker run failed

### ISSUE THREAD

**Issue by flameleo11** [mongo-express/mongo-express#811]
mi@redmi:~/tmp$ docker pull mongo-express
Using default tag: latest
latest: Pulling from library/mongo-express
6a428f9f83b0: Pull complete 
f2b1fb32259e: Pull complete 
40888f2a0a1f: Pull complete 
4e3cc9ce09be: Pull complete 
eaa1898f3899: Pull complete 
ab4078090382: Pull complete 
ae780a42c79e: Pull complete 
e60224d64a04: Pull complete 
Digest: sha256:2a25aafdf23296823b06bc9a0a2af2656971262041b8dbf11b40444804fdc104
Status: Downloaded newer image for mongo-express:latest
docker.io/library/mongo-express:latest
mi@redmi:~/tmp$ docker images|g expres
24:mongo-express                            latest    2d2fb2cabc8f   3 weeks ago    136MB
mi@redmi:~/tmp$ 
mi@redmi:~/tmp$ docker run -it --rm \
>     --name mongo-express \
>     --network web_default \
>     -p 8081:8081 \
>     -e ME_CONFIG_OPTIONS_EDITORTHEME="" \
>     -e ME_CONFIG_BASICAUTH_USERNAME="" \
>     -e ME_CONFIG_MONGODB_URL="mongodb://127.0.0.1:27017" \
>     mongo-express
docker: Error response from daemon: network web_default not found.
mi@redmi:~/tmp$ docker run -it --rm \
>     --name mongo-express \
>     -p 8081:8081 \
>     -e ME_CONFIG_MONGODB_URL="mongodb://127.0.0.1:27017" \
>     mongo-express

Welcome to mongo-express
------------------------

(node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Could not connect to database using connectionString: mongodb://127.0.0.1:27017"
(node:7) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/node_modules/mongodb/lib/core/topologies/server.js:441:11)
    at Pool.emit (events.js:314:20)
    at /node_modules/mongodb/lib/core/connection/pool.js:564:14
    at /node_modules/mongodb/lib/core/connection/pool.js:1000:11
    at /node_modules/mongodb/lib/core/connection/connect.js:32:7
    at callback (/node_modules/mongodb/lib/core/connection/connect.js:300:5)
    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connect.js:330:7)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
mi@redmi:~/tmp$ $ docker run --network some-network -e ME_CONFIG_MONGODB_SERVER=some-mongo -p 8081:8081 mongo-express
$: command not found
mi@redmi:~/tmp$  docker run --network some-network -e ME_CONFIG_MONGODB_SERVER=some-mongo -p 8081:8081 mongo-express
docker: Error response from daemon: network some-network not found.
ERRO[0000] error waiting for container: context canceled 
mi@redmi:~/tmp$ docker run -e ME_CONFIG_MONGODB_SERVER=some-mongo -p 8081:8081 mongo-express
Welcome to mongo-express
------------------------

(node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Could not connect to database using connectionString: mongodb://some-mongo:27017/"
(node:7) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [some-mongo:27017] on first connect [Error: getaddrinfo ENOTFOUND some-mongo
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/node_modules/mongodb/lib/core/topologies/server.js:441:11)
    at Pool.emit (events.js:314:20)
    at /node_modules/mongodb/lib/core/connection/pool.js:564:14
    at /node_modules/mongodb/lib/core/connection/pool.js:1000:11
    at /node_modules/mongodb/lib/core/connection/connect.js:32:7
    at callback (/node_modules/mongodb/lib/core/connection/connect.js:300:5)
    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connect.js:330:7)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
mi@redmi:~/tmp$

**Comment by black1277** [comment]
flameleo11, before using this code, first use it
`docker network create web_default`

**Comment by bobbyy16** [comment]
why is it not working in yaml file

code -

version: '3'
services:
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSER=admin
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb

    

error - 

developing-with-docker-mongo-express-1  | (node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
developing-with-docker-mongo-express-1  | Could not connect to database using connectionString: mongodb://mongodb:27017/"
developing-with-docker-mongo-express-1  | (node:7) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongodb:27017] on first connect [Error: connect ECONNREFUSED 172.19.0.3:27017
developing-with-docker-mongo-express-1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1144:16) {
developing-with-docker-mongo-express-1  |   name: 'MongoNetworkError'
developing-with-docker-mongo-express-1  | }]
developing-with-docker-mongo-express-1  |     at Pool.<anonymous> (/node_modules/mongodb/lib/core/topologies/server.js:441:11)
developing-with-docker-mongo-express-1  |     at Pool.emit (events.js:314:20)
developing-with-docker-mongo-express-1  |     at /node_modules/mongodb/lib/core/connection/pool.js:564:14
developing-with-docker-mongo-express-1  |     at /node_modules/mongodb/lib/core/connection/pool.js:1000:11
developing-with-docker-mongo-express-1  |     at /node_modules/mongodb/lib/core/connection/connect.js:32:7
developing-with-docker-mongo-express-1  |     at callback (/node_modules/mongodb/lib/core/connection/connect.js:300:5)
developing-with-docker-mongo-express-1  |     at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connect.js:330:7)
developing-with-docker-mongo-express-1  |     at Object.onceWrapper (events.js:421:26)
developing-with-docker-mongo-express-1  |     at Socket.emit (events.js:314:20)
developing-with-docker-mongo-express-1  |     at emitErrorNT (internal/streams/destroy.js:92:8)
developing-with-docker-mongo-express-1  |     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
developing-with-docker-mongo-express-1  |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
developing-with-docker-mongo-express-1  | (node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
developing-with-docker-mongo-express-1  | (node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by gabri231** [comment]
If you start manually docker container mongo-express works.

I don't know ehy but it works.

2022-11-29 11:49:31 (node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2022-11-29 11:49:31 (node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2022-11-29 11:50:01 (node:6) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
2022-11-29 11:50:01 Server is open to allow connections from anyone (0.0.0.0)

**Comment by aye-nyeinSan** [comment]
i am facing the same issue . 
Here is my yaml file.
` version: '3'

services:

  mongo:
    image: mongo
    restart: always
    environment:
    - MONGO_INITDB_ROOT_USERNAME=ayeNyeinSan
    - MONGO_INITDB_ROOT_PASSWORD=test123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/`
      
Here is the log file.
`Welcome to mongo-express
------------------------


(node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Could not connect to database using connectionString: mongodb://root:password@mongodb:27017/"
(node:7) UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [mongodb:27017] on first connect [Error: getaddrinfo EAI_AGAIN mongodb
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  name: 'MongoNetworkError'
}]
    at Pool.<anonymous> (/node_modules/mongodb/lib/core/topologies/server.js:441:11)
    at Pool.emit (events.js:314:20)
    at /node_modules/mongodb/lib/core/connection/pool.js:564:14
    at /node_modules/mongodb/lib/core/connection/pool.js:1000:11
    at /node_modules/mongodb/lib/core/connection/connect.js:32:7
    at callback (/node_modules/mongodb/lib/core/connection/connect.js:300:5)
    at Socket.<anonymous> (/node_modules/mongodb/lib/core/connection/connect.js:330:7)
    at Object.onceWrapper (events.js:421:26)
    at Socket.emit (events.js:314:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:7) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:7) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

It would be a great help if someone helps me.

**Comment by black1277** [comment]
[aye-nyeinSan](https://github.com/aye-nyeinSan)
Use this [config ](https://github.com/black1277/mongo-express/blob/master/docker-compose.yml)

**Comment by ShanmugaSrinivasan993** [comment]
@black1277 your config file helped me resolve the issue. I just used "restart: unless-stopped" and it worked. Thanks
