### ISSUE TITLE
Using ME_CONFIG_MONGODB_CA_FILE throws ERR_INVALID_ARG_TYPE 

### ISSUE THREAD

**Issue by BlackthornYugen** [mongo-express/mongo-express#814]
If you try to give the CA as an array of certificates you get this exception:

```
[0] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Array
[0]     at Object.openSync (node:fs:577:10)
[0]     at Object.readFileSync (node:fs:453:35)
[0]     at /Users/stj1mis/vcs/github.com/mongo-express/node_modules/mongodb/lib/operations/connect.js:253:32
[0]     at Array.forEach (<anonymous>)
[0]     at resolveTLSOptions (/Users/stj1mis/vcs/github.com/mongo-express/node_modules/mongodb/lib/operations/connect.js:251:34)
[0]     at /Users/stj1mis/vcs/github.com/mongo-express/node_modules/mongodb/lib/operations/connect.js:310:5
[0]     at parseConnectionString (/Users/stj1mis/vcs/github.com/mongo-express/node_modules/mongodb/lib/core/uri_parser.js:720:3)
[0]     at connect (/Users/stj1mis/vcs/github.com/mongo-express/node_modules/mongodb/lib/operations/connect.js:282:3)
[0]     at /Users/stj1mis/vcs/github.com/mongo-express/node_modules/mongodb/lib/mongo_client.js:223:5
[0]     at maybePromise (/Users/stj1mis/vcs/github.com/mongo-express/node_modules/mongodb/lib/utils.js:662:3)
```

It would appear that the driver now wants a path to a PEM file. Maybe this worked on a previous version?

**Comment by BlackthornYugen** [comment]
Reproduction steps:

1.  Copy config

```bash
cp config.default.js config.js
```

2. Try to connect to any url with TLS on

```bash
ME_CONFIG_MONGODB_URL='mongodb://fake:fake@127.0.0.1/?authSource=admin&tls=true' node app

Welcome to mongo-express
------------------------


Could not connect to database using connectionString: mongodb://fake:fake@127.0.0.1/?authSource=admin&tls=true"
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Array
    at Object.openSync (node:fs:577:10)
    at Object.readFileSync (node:fs:453:35)
    at /Users/stj1mis/vcs/github.com/mongo-express/node_modules/mongodb/lib/operations/connect.js:253:32
    at Array.forEach (<anonymous>)
    at resolveTLSOptions (/Users/stj1mis/vcs/github.com/mongo-express/node_modules/mongodb/lib/operations/connect.js:251:34)
    at /Users/stj1mis/vcs/github.com/mongo-express/node_modules/mongodb/lib/operations/connect.js:310:5
    at parseConnectionString (/Users/stj1mis/vcs/github.com/mongo-express/node_modules/mongodb/lib/core/uri_parser.js:720:3)
    at connect (/Users/stj1mis/vcs/github.com/mongo-express/node_modules/mongodb/lib/operations/connect.js:282:3)
    at /Users/stj1mis/vcs/github.com/mongo-express/node_modules/mongodb/lib/mongo_client.js:223:5
    at maybePromise (/Users/stj1mis/vcs/github.com/mongo-express/node_modules/mongodb/lib/utils.js:662:3)
    at MongoClient.connect (/Users/stj1mis/vcs/github.com/mongo-express/node_modules/mongodb/lib/mongo_client.js:219:10)
    at Function.MongoClient.connect (/Users/stj1mis/vcs/github.com/mongo-express/node_modules/mongodb/lib/mongo_client.js:442:22)
    at /Users/stj1mis/vcs/github.com/mongo-express/lib/db.js:97:37
    at tryCatcher (/Users/stj1mis/vcs/github.com/mongo-express/node_modules/bluebird/js/release/util.js:16:23)
    at Function.Promise.fromNode.Promise.fromCallback (/Users/stj1mis/vcs/github.com/mongo-express/node_modules/bluebird/js/release/promise.js:209:30)
    at /Users/stj1mis/vcs/github.com/mongo-express/lib/db.js:96:37 {
  code: 'ERR_INVALID_ARG_TYPE'
}

Node.js v17.0.1

```

**Comment by BlackthornYugen** [comment]
Think I found the breaking change. It looks like the option "sslCert" has been mapped to the closest TLS option "tlsCAFile".

from mongo_client.js:
```
* @param {buffer} [options.sslCert=undefined] SSL Certificate binary buffer *deprecated* use `tls` variants
* @param {string} [options.tlsCAFile] A path to file with either a single or bundle of certificate authorities to be considered trusted when making a TLS connection
```

see also: https://github.com/mongodb/specifications/blob/ce242ddbb5377c509057e4e07b9d56c011bb0229/source/uri-options/uri-options.rst
