### ISSUE TITLE
unable to list databases:  Error [MongoError]: not master and slaveOk=false

### ISSUE THREAD

**Issue by shibumi** [mongo-express/mongo-express#816]
Hi,

I am running mongo-express with 3 containers on a kubernetes clusters. They are connecting to a mongodb cluster with 2 mongodb instances and one mongodb-arbiter pod. All other of our platforms have no problems connecting to the mongodb cluster, nor do they have "notMaster" problems. Mongo Express version: 0.54.0

The mongodb is configured with the bitnami mongodb chart:

```
- name: mongodb
--
  | repository: https://charts.bitnami.com/bitnami
  | version: 10.23.9
```

Here is the full stackTrace:
```
unable to list databases
Error [MongoError]: not master and slaveOk=false
    at Function.MongoError.create (/node_modules/mongodb-core/lib/error.js:31:11)
    at /node_modules/mongodb-core/lib/connection/pool.js:483:72
    at authenticateStragglers (/node_modules/mongodb-core/lib/connection/pool.js:429:16)
    at Connection.messageHandler (/node_modules/mongodb-core/lib/connection/pool.js:463:5)
    at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:319:22)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
  topologyVersion: { processId: 619fad3f3cb8af6b3fd1838c, counter: 8 },
  operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1638266856 },
  ok: 0,
  errmsg: 'not master and slaveOk=false',
  code: 13435,
  codeName: 'NotPrimaryNoSecondaryOk',
  '$clusterTime': {
    clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1638266856 },
    signature: { hash: [Binary], keyId: [Long] }
  }
}
```

**Comment by alorka** [comment]
Same here :S

**Comment by emimarz** [comment]
same here

**Comment by shibumi** [comment]
@alorka @emimarz  My colleague fixed this issue via addressing the mongodb admin node as target.. but this destroys the whole concept of non-administrator nodes with mongodb :S (at least it works)

**Comment by idrissneumann** [comment]
Same here, still no news on this mater ?

![Screenshot 2022-12-23 at 19 33 20](https://user-images.githubusercontent.com/12884347/209392366-3cac7570-4b49-4da2-8b76-8e10fc9d5660.png)

**Comment by rtritto** [comment]
Did you try adding _readPreference_ in connection string? ([source](https://www.mongodb.com/community/forums/t/node-js-driver-3-6-3-with-replica-set-not-master-and-slaveok-false/127208/6))

_readPreference_ value is one of [Read Preference Mode](https://www.mongodb.com/docs/manual/core/read-preference).

**Comment by xtso520ok** [comment]
![image](https://github.com/mongo-express/mongo-express/assets/2193059/4c216144-c7e0-49c3-bb94-972b7a6a5836)

usage mongo-express:1.0.0-alpha.4 is OK
