### ISSUE TITLE
Pagination seems broken for time series collections

### ISSUE THREAD

**Issue by xAslan** [mongo-express/mongo-express#848]
Using mongo:5.0.5-focal
mongo-express:latest

when trying to page through time-series collections the pagination only shows page 1 and the next, prev, first, and last buttons are all disabled. You can still manually add ?skip=10 to the URL to page through, but the UI is broken

**Comment by vlebedenko** [comment]
Is there any solution with the problem ? 
Faced the same when cleaned my collections from garbage documents by my Python script. Mongo DB version 4.1.0.
There is no possibility in any collection to go next or prev page with documents.

**Comment by Ilya-VK** [comment]
Same here, 1.0.0-18-alpine3.18 image, pagination doesn't switch pages, just reloads to page 1.

**Comment by tsankuanglee** [comment]
confirming this UI bug existing in both `1.0.0-18-alpine3.17` and `1.0.0-20-alpine3.18` images.

**Comment by krokodile-spb** [comment]
Same problem with images 1.0-20-alpine3.18, 1.0-18-alpine3.18
While pagination I got this error in docker shell:


```
MongoInvalidArgumentError: Argument "pipeline" must be an array of aggregation stages
    at Collection.aggregate (/node_modules/mongodb/lib/collection.js:368:19)
    at exp.viewCollection (/node_modules/mongo-express/lib/routes/collection.js:167:26)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:144:13)
    at mongoMiddleware (/node_modules/mongo-express/lib/router.js:260:5)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at /node_modules/express/lib/router/index.js:284:15 {
  [Symbol(errorLabels)]: Set(0) {}
}
GET /db/main/ih_acc?skip=10&key=&value=&type=&query=&projection=&runAggregate=false 302 32.633 ms - 126
GET /db/main/ih_acc 304 469.876 ms - -
```

**Comment by pciavald** [comment]
same here, but i see a 302 and i'm running behind a reverse proxy with `ME_CONFIG_SITE_BASEURL: /mongo` in case it helps
```
cosmos-mongo-express  | MongoInvalidArgumentError: Argument "pipeline" must be an array of aggregation stages
cosmos-mongo-express  |     at Collection.aggregate (/node_modules/mongodb/lib/collection.js:368:19)
cosmos-mongo-express  |     at exp.viewCollection (/node_modules/mongo-express/lib/routes/collection.js:167:26)
cosmos-mongo-express  |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
cosmos-mongo-express  |     at next (/node_modules/express/lib/router/route.js:144:13)
cosmos-mongo-express  |     at mongoMiddleware (/node_modules/mongo-express/lib/router.js:260:5)
cosmos-mongo-express  |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
cosmos-mongo-express  |     at next (/node_modules/express/lib/router/route.js:144:13)
cosmos-mongo-express  |     at Route.dispatch (/node_modules/express/lib/router/route.js:114:3)
cosmos-mongo-express  |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
cosmos-mongo-express  |     at /node_modules/express/lib/router/index.js:284:15 {
cosmos-mongo-express  |   [Symbol(errorLabels)]: Set(0) {}
cosmos-mongo-express  | }
cosmos-mongo-express  | GET /mongo/db/mydb/events?skip=10&key=&value=&type=&query=&projection=&runAggregate=false 302 21.351 ms - 130
```

**Comment by FrancescoSaverioZuppichini** [comment]
same issue here

**Comment by Devesh222** [comment]
same issue here.

**Comment by FrancescoSaverioZuppichini** [comment]
I've installed an earlier version

**Comment by F-Node-Karlsruhe** [comment]
> I've installed an earlier version

Which one is working for your? Same issue here

**Comment by sanderPostma** [comment]
> > I've installed an earlier version
> 
> Which one is working for your? Same issue here

Went back to image mongo-express:1.0.0-alpha.4

**Comment by Tesax123** [comment]
Same issue, going back to image mongo-express:1.0.0-alpha.4 worked.

**Comment by mat-tia** [comment]
yes it's broken, because the runAggregate parameter is broken which is added to the link.

Which would result in the log output of @pciavald.

So- annoying workaround: hover over the button, copy the link, post it in the address bar and delete the &runAggregate=false parameter. 

I believe the checkbox for aggregate queries under the advance tab would also not work because of this.

**Comment by mat-tia** [comment]
Btw. this is fixed in the latest docker image running on alpine 3.18.5 and node:18 with express 1.0.2. The runAggregate parameter has been removed from pagination.

**Comment by Bennyphoto-gallery6** [comment]
@krokodile-spb https://stackdev.space/questions/combining-arrays-in-mongodb
