### ISSUE TITLE
Deprecated API removed in MongoDB 6.0

### ISSUE THREAD

**Issue by bjornlaurell** [mongo-express/mongo-express#887]
Getting following the errors when running mongo-express 0.54.0 against MongoDB 6.0.1:

```
unable to list databases
Error [MongoError]: Unsupported OP_QUERY command: listDatabases. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal
at Function.MongoError.create (/node_modules/mongodb-core/lib/error.js:31:11)
at /node_modules/mongodb-core/lib/connection/pool.js:483:72
at authenticateStragglers (/node_modules/mongodb-core/lib/connection/pool.js:429:16)
at Connection.messageHandler (/node_modules/mongodb-core/lib/connection/pool.js:463:5)
at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:319:22)
at Socket.emit (events.js:314:20)
at addChunk (_stream_readable.js:297:12)
at readableAddChunk (_stream_readable.js:272:9)
at Socket.Readable.push (_stream_readable.js:213:10)
at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
ok: 0,
errmsg: 'Unsupported OP_QUERY command: listDatabases. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal',
code: 352,
codeName: 'UnsupportedOpQueryCommand',
'$clusterTime': {
clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1661438538 },
signature: { hash: [Binary], keyId: [Long] }
},
operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1661438538 }
}
Error [MongoError]: Unsupported OP_QUERY command: serverStatus. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal
at Function.MongoError.create (/node_modules/mongodb-core/lib/error.js:31:11)
at /node_modules/mongodb-core/lib/connection/pool.js:483:72
at authenticateStragglers (/node_modules/mongodb-core/lib/connection/pool.js:429:16)
at Connection.messageHandler (/node_modules/mongodb-core/lib/connection/pool.js:463:5)
at Socket.<anonymous> (/node_modules/mongodb-core/lib/connection/connection.js:319:22)
at Socket.emit (events.js:314:20)
at addChunk (_stream_readable.js:297:12)
at readableAddChunk (_stream_readable.js:272:9)
at Socket.Readable.push (_stream_readable.js:213:10)
at TCP.onStreamRead (internal/stream_base_commons.js:188:23) {
ok: 0,
errmsg: 'Unsupported OP_QUERY command: serverStatus. The client driver may require an upgrade. For more details see https://dochub.mongodb.org/core/legacy-opcode-removal',
code: 352,
codeName: 'UnsupportedOpQueryCommand',
'$clusterTime': {
clusterTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1661438538 },
signature: { hash: [Binary], keyId: [Long] }
},
operationTime: Timestamp { _bsontype: 'Timestamp', low_: 1, high_: 1661438538 }
}
```

**Comment by shakaran** [comment]
@bjornlaurell I think that the progress in latest alphas are for Mongo 4, but pull request are welcome for support mongo 5 or mongo 6

**Comment by gong4soft** [comment]
@shakaran  can you please post the issue/link which is for Mongo 4, I would like to check any posibilities to do for Mongo 6.

**Comment by shakaran** [comment]
> @shakaran can you please post the issue/link which is for Mongo 4, I would like to check any posibilities to do for Mongo 6.

https://github.com/mongo-express/mongo-express/issues/887

**Comment by BlackthornYugen** [comment]
> Getting following the errors when running mongo-express 0.54.0 against MongoDB 6.0.1:

@bjornlaurell  Can you try with the recently released mongo-express 1.0.0?

![image](https://user-images.githubusercontent.com/3138467/189260801-3ac1aaab-087b-49e4-8d69-a9d2b7d5cb61.png)

**Comment by BlackthornYugen** [comment]
> @shakaran can you please post the issue/link which is for Mongo 4, I would like to check any posibilities to do for Mongo 6.

#857 Updated from 3.6.2 to 4.9.0
#918 Updated from 4.9.0 to 4.9.1

Both of those changes were done long after mongo-express 0.54.0. It seems that mongo-express 1.0.0 with the latest v4 client driver should support (or at least partially support?) mongo v6.

**Comment by gong4soft** [comment]
@BlackthornYugen I verifed version mongo-express:1.0.0-alpha.4 against mongo 6.0.1, no error comes out.

**Comment by BlackthornYugen** [comment]
1.0.0 was published to NPM yesterday :)

**Comment by hldh214** [comment]
> 1.0.0 was published to NPM yesterday :)

What about docker image

**Comment by BlackthornYugen** [comment]
> > 1.0.0 was published to NPM yesterday :)
> 
> What about docker image

Working to get the docker image updated, you can track our progress here:
https://github.com/docker-library/official-images/pull/13162#issuecomment-1249712413

If you need a 1.0.0 docker image today, ghcr.io/blackthornyugen/mongo-express-docker:v1.0.0 can be used but you should switch to the official once it's out.

**Comment by Xeroxxx** [comment]
Alpha 4 works for me loading small collections but not large collections, which were loaded in seconds before. 

Can't see any log entries except repeated "connection accpeted" and "autentication succeded"

**Comment by Xeroxxx** [comment]
So latest container (alpha4) still not fully working for me on 6.0.x. I can open collections with roughly 300.000 small entries (avg doc size 204 byte). But I can't open collections with 6.000.000 entries+ and avg doc size of 23kb. It just times out (xx.xx.xx.xxx didn’t send any data. ERR_EMPTY_RESPONSE). The whole application is stuck during this and does not respond. I can see mongod running on high load.

There is no error message in the logs.

Did the "View" query change in this release?

**Comment by bjornlaurell** [comment]
Getting the following warnings when running mongo-express:1.0.0-alpha.4 against mongo:6.0.4:
`(node:7) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.`
`(node:7) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use Collection.countDocuments or Collection.estimatedDocumentCount instead`

Also the Server Status field displays: "Turn on admin in config.js to view server stats!" even with  `ME_CONFIG_MONGODB_ENABLE_ADMIN=true`

Other then that it seems to be working.

**Comment by bjornlaurell** [comment]
`TypeError: mongo.connections[req.dbName].collection is not a function
    at /node_modules/mongo-express/lib/router.js:222:35
    at paramCallback (/node_modules/express/lib/router/index.js:404:7)
    at param (/node_modules/express/lib/router/index.js:384:5)
    at paramCallback (/node_modules/express/lib/router/index.js:401:21)
    at /node_modules/mongo-express/lib/router.js:114:5
    at paramCallback (/node_modules/express/lib/router/index.js:404:7)
    at param (/node_modules/express/lib/router/index.js:384:5)
    at Function.process_params (/node_modules/express/lib/router/index.js:410:3)
    at next (/node_modules/express/lib/router/index.js:275:10)
    at next (/node_modules/express/lib/router/route.js:127:14)
    at /node_modules/mongo-express/lib/router.js:96:7
    at tryCatcher (/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/node_modules/bluebird/js/release/promise.js:729:18)`

Crash when trying to view a GridFS bucket

(mongo-express:1.0.0-alpha.4 against mongo:6.0.4:)

**Comment by xtso520ok** [comment]
https://github.com/mongo-express/mongo-express/issues/816#issuecomment-1606511119

**Comment by amiht** [comment]
> I tried with mongo docker image 6.0.3 & mongo-express docker image 1.0.0-alpha.4. which is working fine.

Really It is working for me.

**Comment by amiht** [comment]
After all I tried with mongo docker image 6.0 & mongo-express docker image 1.0.0-alpha.4. It is working fine.
