### ISSUE TITLE
The docker image built from tag v1.0.0 seems to be broken

### ISSUE THREAD

**Issue by denist-huma** [mongo-express/mongo-express#956]
## My clause 

I want use `mongo-express` docker image to connect to Atlas MongoDB. I know that there 3+ Atlas related isues in this repo

My URI looks like ME_CONFIG_MONGODB_URL="mongodb+srv://2627-db:PASS@MY-CLUSTER.mongodb.net/2627-db?authSource=admin"

There is an advice to edit "config.js"  I haven't tried https://github.com/mongo-express/mongo-express/issues/584#issuecomment-800803419

The "latest" docker that is 1 year old, "1.0.0-alpha.4" still contains this bug.

The Mongo Shell is working with my URI:

```sh
$ mongosh mongodb+srv://2627-db:PASS@MY-CLUSTER.mongodb.net/2627-db?authSource=admin
Current Mongosh Log ID: 6320567cf31460f5da1131ae
Connecting to:          mongodb+srv://<credentials>@MY-CLUSTER..mongodb.net/2627-db?authSource=admin&appName=mongosh+1.5.4
Using MongoDB:          4.2.22
Using Mongosh:          1.5.4

For mongosh info see: https://docs.mongodb.com/mongodb-shell/

Atlas atlas-######-shard-0 [primary] 2627-db>
```

## reproduce

```sh
git checkout v1.0.0
docker build -t mongo-express:1.0.0 .
$ docker run -it --rm     --name mongo-express -p 8081:8081     -e ME_CONFIG_OPTIONS_EDITORTHEME="ambiance"     -e ME_CONFIG_MONGODB_URL="mongodb+srv://2627-db:PASS@MY-CLUSTER.mongodb.net/2627-db?authSource=admin"     mongo-express:1.0.0
> mongo-express@1.0.0 start
> cross-env NODE_ENV=production node app

Welcome to mongo-express
------------------------


Could not connect to database using connectionString: mongodb+srv://2627-db:PASS@MY-CLUSTER.mongodb.net/2627-db?authSource=admin"
node:fs:599
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open
    at Object.openSync (node:fs:599:3)
    at Object.readFileSync (node:fs:467:35)
    at transform (/app/node_modules/mongodb/lib/connection_string.js:903:23)
    at setOption (/app/node_modules/mongodb/lib/connection_string.js:442:36)
    at parseOptions (/app/node_modules/mongodb/lib/connection_string.js:297:9)
    at new MongoClient (/app/node_modules/mongodb/lib/mongo_client.js:65:63)
    at MongoClient.connect (/app/node_modules/mongodb/lib/mongo_client.js:233:33)
    at /app/lib/db.js:90:48
    at Array.map (<anonymous>)
    at connect (/app/lib/db.js:85:58) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT'
}

Node.js v18.7.0
```

**Comment by rtritto** [comment]
Can you try:
```
ME_CONFIG_MONGODB_SSL="true"
ME_CONFIG_MONGODB_SSLVALIDATE="false"
```

**Comment by BlackthornYugen** [comment]
> You can try to add:
> 
> ```
> ME_CONFIG_MONGODB_SSL="true"
> ME_CONFIG_MONGODB_SSLVALIDATE="false"
> ```

Good to try for debugging but we would not recommend disabling TLS validation in production. Keep in mind that others with similar issues may find this thread )

**Comment by BlackthornYugen** [comment]
Misclicked close by mistake.

**Comment by radokristof** [comment]
I'm also having problems with this.
I'm using a reverse proxy, so I don't need any authentication.

However I can't turn off basicauth:
```
      - ME_CONFIG_BASICAUTH_USERNAME=""
      - ME_CONFIG_BASICAUTH_PASSWORD=""
```
And still asks for password

**Comment by BlackthornYugen** [comment]
@denist-huma are you removing the user/password from the connection string before you paste the logs or are they not showing at all?

**Comment by BlackthornYugen** [comment]
> And still asks for password (but nothing works)

This sounds like a different issue, but if the BASICAUTH_USERNAME is blank it [should set useBasicAuth to false](https://github.com/mongo-express/mongo-express/blob/3a3648ebb78ec5eccb73162bafacd5ef03a1e358/config.default.js#L137) and when it is false, it [should not use basic auth](https://github.com/mongo-express/mongo-express/blob/3a3648ebb78ec5eccb73162bafacd5ef03a1e358/lib/router.js#L29-L31). Can you open a separate ticket so that we can help troubleshoot?

**Comment by radokristof** [comment]
@BlackthornYugen yes, sure, sorry I just had a quick glance at the issue and it seemed similar to my issue.

**Comment by denist-huma** [comment]
> @denist-huma are you removing the user/password from the connection string before you paste the logs or are they not showing at all?

I don't mean to be unclear, but I cut user. password in both the log and command before pasting it here. I know that my MongoDB URI is correct since I can connect with `mongosh` from the same PC, same IP.

**Comment by BlackthornYugen** [comment]
@denist-huma I was able to reproduce this on master

<img width="1152" alt="image" src="https://user-images.githubusercontent.com/3138467/190520144-5ef9dceb-923d-43a5-ad4b-6ff6b745790b.png">


<details>
  <summary>Expand for full error output:


```shell

Could not connect to database using connectionString: mongodb+srv://jsteelkw:****@cluster0.wmg3grn.mongodb.net/?retryWrites=true&w=majority"
/Users/jsteel/vcs/mongo-express/node_modules/mongodb/lib/sdam/topology.js:293
                const timeoutError = new error_1.MongoServerSelectionError(`Server selection timed out after ${serverSelectionTimeoutMS} ms`, this.description);
```
</summary>
  
  ```shell
/opt/homebrew/bin/node /Users/jsteel/vcs/mongo-express/app.js
No custom config.js found, loading config.default.js
Welcome to mongo-express
------------------------


Could not connect to database using connectionString: mongodb+srv://jsteelkw:****@cluster0.wmg3grn.mongodb.net/?retryWrites=true&w=majority"
/Users/jsteel/vcs/mongo-express/node_modules/mongodb/lib/sdam/topology.js:293
                const timeoutError = new error_1.MongoServerSelectionError(`Server selection timed out after ${serverSelectionTimeoutMS} ms`, this.description);
                                     ^

MongoServerSelectionError: connection <monitor> to 44.227.10.63:27017 closed
    at Timeout._onTimeout (/Users/jsteel/vcs/mongo-express/node_modules/mongodb/lib/sdam/topology.js:293:38)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7) {
  reason: TopologyDescription {
    type: 'ReplicaSetNoPrimary',
    servers: Map(3) {
      'ac-mdx9zen-shard-00-00.wmg3grn.mongodb.net:27017' => ServerDescription {
        address: 'ac-mdx9zen-shard-00-00.wmg3grn.mongodb.net:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 888119131,
        lastWriteDate: 0,
        error: MongoNetworkError: connection <monitor> to 44.227.10.63:27017 closed
            at Connection.onClose (/Users/jsteel/vcs/mongo-express/node_modules/mongodb/lib/cmap/connection.js:135:19)
            at Socket.<anonymous> (/Users/jsteel/vcs/mongo-express/node_modules/mongodb/lib/cmap/connection.js:62:46)
            at Socket.emit (node:events:513:28)
            at TCP.<anonymous> (node:net:313:12) {
          [Symbol(errorLabels)]: Set(0) {}
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      },
      'ac-mdx9zen-shard-00-01.wmg3grn.mongodb.net:27017' => ServerDescription {
        address: 'ac-mdx9zen-shard-00-01.wmg3grn.mongodb.net:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 888118674,
        lastWriteDate: 0,
        error: MongoNetworkError: connection <monitor> to 100.20.237.215:27017 closed
            at Connection.onClose (/Users/jsteel/vcs/mongo-express/node_modules/mongodb/lib/cmap/connection.js:135:19)
            at Socket.<anonymous> (/Users/jsteel/vcs/mongo-express/node_modules/mongodb/lib/cmap/connection.js:62:46)
            at Socket.emit (node:events:513:28)
            at TCP.<anonymous> (node:net:313:12) {
          [Symbol(errorLabels)]: Set(0) {}
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      },
      'ac-mdx9zen-shard-00-02.wmg3grn.mongodb.net:27017' => ServerDescription {
        address: 'ac-mdx9zen-shard-00-02.wmg3grn.mongodb.net:27017',
        type: 'Unknown',
        hosts: [],
        passives: [],
        arbiters: [],
        tags: {},
        minWireVersion: 0,
        maxWireVersion: 0,
        roundTripTime: -1,
        lastUpdateTime: 888118663,
        lastWriteDate: 0,
        error: MongoNetworkError: connection <monitor> to 100.21.165.250:27017 closed
            at Connection.onClose (/Users/jsteel/vcs/mongo-express/node_modules/mongodb/lib/cmap/connection.js:135:19)
            at Socket.<anonymous> (/Users/jsteel/vcs/mongo-express/node_modules/mongodb/lib/cmap/connection.js:62:46)
            at Socket.emit (node:events:513:28)
            at TCP.<anonymous> (node:net:313:12) {
          [Symbol(errorLabels)]: Set(0) {}
        },
        topologyVersion: null,
        setName: null,
        setVersion: null,
        electionId: null,
        logicalSessionTimeoutMinutes: null,
        primary: null,
        me: null,
        '$clusterTime': null
      }
    },
    stale: false,
    compatible: true,
    heartbeatFrequencyMS: 10000,
    localThresholdMS: 15,
    setName: 'atlas-kmdj2s-shard-0',
    maxElectionId: null,
    maxSetVersion: null,
    commonWireVersion: 0,
    logicalSessionTimeoutMinutes: null
  },
  code: undefined,
  [Symbol(errorLabels)]: Set(0) {}
}

Node.js v18.8.0

Process finished with exit code 1


  ```
  
</details>

**Comment by BlackthornYugen** [comment]
Just adding ME_CONFIG_MONGODB_SSL=true seems to allow me to connect to atlas and interact with a test database I created, but it looks like I don't have permission to list databases?

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/3138467/190524179-0479320c-ab49-4c1f-acfb-fa1d53943235.png">

<details>
  <summary>Click to show full output


```shell
docker run -it --rm -p 8081:8081 -e ME_CONFIG_MONGODB_SSL=true -e "ME_CONFIG_MONGODB_URL=mongodb+srv://jsteelkw:$MONGO_PASSWORD@cluster0.wmg3grn.mongodb.net/?retryWrites=true&w=majority" ghcr.io/blackthornyugen/mongo-express-docker:v1.0.0
No custom config.js found, loading config.default.js
Welcome to mongo-express
------------------------


Mongo Express server listening at http://0.0.0.0:8081
```
</summary>

  
  ```shell
Mongo Express server listening at http://0.0.0.0:8081
Server is open to allow connections from anyone (0.0.0.0)
basicAuth credentials are "admin:pass", it is recommended you change this in your config.js!
MongoServerError: user is not allowed to do action [serverStatus] on [admin.]
    at Connection.onMessage (/app/node_modules/mongodb/lib/cmap/connection.js:207:30)
    at MessageStream.<anonymous> (/app/node_modules/mongodb/lib/cmap/connection.js:60:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:132:20)
    at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at TLSSocket.ondata (node:internal/streams/readable:766:22)
    at TLSSocket.emit (node:events:513:28) {
  ok: 0,
  code: 8000,
  codeName: 'AtlasError',
  [Symbol(errorLabels)]: Set(0) {}
}
GET / - - ms - -
GET / - - ms - -
MongoServerError: user is not allowed to do action [serverStatus] on [admin.]
    at Connection.onMessage (/app/node_modules/mongodb/lib/cmap/connection.js:207:30)
    at MessageStream.<anonymous> (/app/node_modules/mongodb/lib/cmap/connection.js:60:60)
    at MessageStream.emit (node:events:513:28)
    at processIncomingData (/app/node_modules/mongodb/lib/cmap/message_stream.js:132:20)
    at MessageStream._write (/app/node_modules/mongodb/lib/cmap/message_stream.js:33:9)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at TLSSocket.ondata (node:internal/streams/readable:766:22)
    at TLSSocket.emit (node:events:513:28) {
  ok: 0,
  code: 8000,
  codeName: 'AtlasError',
  [Symbol(errorLabels)]: Set(0) {}
}
GET /db/test/ - - ms - -
GET /db/test/ 200 1405.020 ms - 9096
GET /public/css/style.css 200 2.931 ms - 1883
GET /public/css/bootstrap.min.css 200 5.864 ms - 121457
GET /public/css/bootstrap-theme.min.css 200 3.368 ms - 23411
GET /public/database-019de86007d9d924e860.min.js 200 3.194 ms - 1518
GET /public/vendor-29c8f8a1a8783a10b310.min.js 200 3.001 ms - 131097
GET /public/img/mongo-express-logo.png 200 0.617 ms - 17847


  ```
  
</details>

**Comment by BlackthornYugen** [comment]
It seems like the index page doesn't render if it fails to get server status. There is a todo to handle the error better. It looks like if we just render the page in the catch we can at least show the db list. 
<img width="552" alt="image" src="https://user-images.githubusercontent.com/3138467/190525510-9e177c9b-2bb9-487b-9500-4252a94f2895.png">

@denist-huma can you try to go directly to a db page and skip the index? If you loaded the atlas sample data into your sandbox env this should work: http://localhost:8081/db/sample_airbnb/

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/3138467/190525673-348121a6-9eb4-469e-bed1-066c3208c182.png">

**Comment by denist-huma** [comment]
@BlackthornYugen big thanks!
I confurm the my DB page is working `http://0.0.0.0:8081/db/ppserver-2627-db`.
I create a least priveleged user that has readWrite role only for this one database, it cannot list databases.

@BlackthornYugen one more, since I use the *mongo-express* docker image already (older version) in the CI, and my helm chart, is the download path `ghcr.io/blackthornyugen/mongo-express-docker:v1.0.0` is reliable or I gonna hit a download limit?

**Comment by BlackthornYugen** [comment]
I think ghcr has a higher rate limit than dockerhub for anonymous downloads. Should be fine to use for now, but once we publish on dockerhub it might be better to switch to the official release.

I might delete my fork someday so it's probably not good to use in a production environment.

**Comment by denist-huma** [comment]
@BlackthornYugen @rtritto your combined efforts now really made a change for me! :+1::100:  
For our IDP, other ways to access our Atlas MongoDB have limitations I don't want to solve now. 

> ⛁ You can access your Atlas MongoDB using:

> - *MongoDB Compass* or *MongoDB Shell*, run in a shell `mongosh "{{ .mongo_uri }}"`.
>   Please make sure your IP is included in the [IP Access List]
> - [Atlas Cluster control panel].
>   You got to have access to the Atlas project `{{ .atlas_project }}`.

**Comment by denist-huma** [comment]
@rtritto I saw you fixed this bug https://github.com/mongo-express/mongo-express/issues/944, but it is present in a docker now. please suggest me something, I cannot go back to `mongo-express:latest `.

```
MongoInvalidArgumentError: Argument "pipeline" must be an array of aggregation stages                                                                                                                         
    at Collection.aggregate (/app/node_modules/mongodb/lib/collection.js:370:19)                                                                                                                              
    at exp.viewCollection (/app/lib/routes/collection.js:167:26)                                                                                                                                              
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)                                                                                                                  
    at next (/app/node_modules/express/lib/router/route.js:144:13)                                                                                                                                            
    at mongoMiddleware (/app/lib/router.js:260:5)                                                                                                                                                             
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)                                                                                                                  
    at next (/app/node_modules/express/lib/router/route.js:144:13)                                                                                                                                            
    at Route.dispatch (/app/node_modules/express/lib/router/route.js:114:3)                                                                                                                                   
    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)                                                                                                                  
    at /app/node_modules/express/lib/router/index.js:284:15 {                                                                                                                                                 
  [Symbol(errorLabels)]: Set(0) {}                                                                                                                                                                            
}                                                                                                                                                                                                             
GET /mongo-express/db/ppserver-152-db/_databasemigration?skip=10&key=&value=&type=&query=&projection=&runAggregate=false 302 17.234 ms - 214                                                                  
GET /mongo-express/db/ppserver-152-db/_databasemigration 304 55.344 ms - -                                                                                                                                    
GET /mongo-express/public/css/bootstrap.min.css 304 1.974 ms - -                                                                                                                                              
GET /mongo-express/public/css/bootstrap-theme.min.css 304 1.735 ms - -                                                                                                                                        
GET /mongo-express/public/css/style.css 304 1.633 ms - -                                                                                                                                                      
GET /mongo-express/public/css/codemirror.css 304 1.559 ms - -                                                                                                                                                 
GET /mongo-express/public/css/theme/ambiance.css 304 1.544 ms - -                                                                                                                                             
GET /mongo-express/public/vendor-29c8f8a1a8783a10b310.min.js 304 4.702 ms - -                                                                                                                                 
GET /mongo-express/public/collection-3d459cd0f8c24d272db7.min.js 304 4.586 ms - -                                                                                                                             
GET /mongo-express/public/codemirror-329618172969bfe00f90.min.js 304 4.483 ms - -                                                                                                                             
GET /mongo-express/public/img/mongo-express-logo.png 304 4.386 ms - -                                                                                                                                         
GET /mongo-express/public/img/gears.gif 304 4.924 ms - -   
```

**Comment by BlackthornYugen** [comment]
@denist-huma we had a setback getting 1.0.0 published to dockerhub and we might go directly to 1.0.1. Can you check if this build works for you? `ghcr.io/blackthornyugen/mongo-express-docker:v1.0.1-rc3`

**Comment by denist-huma** [comment]
> @denist-huma we had a setback getting 1.0.0 published to dockerhub and we might go directly to 1.0.1. Can you check if this build works for you? ~`ghcr.io/blackthornyugen/mongo-express-docker:v1.0.1-rc3`~ _edit_: Nevermind -- I don't think I built it correctly.

```
node:fs:599                                                                                                                                                                                                   
  handleErrorFromBinding(ctx);                                                                                                                                                                                
  ^                                                                                                                                                                                                           
                                                                                                                                                                                                              
Error: ENOENT: no such file or directory, open './build-assets.json'                                                                                                                                          
    at Object.openSync (node:fs:599:3)                                                                                                                                                                        
    at Object.readFileSync (node:fs:467:35)                                                                                                                                                                   
    at file:///node_modules/mongo-express/lib/middleware.js:9:30                                                                                                                                              
    at ModuleJob.run (node:internal/modules/esm/module_job:193:25)                                                                                                                                            
    at async Promise.all (index 0)                                                                                                                                                                            
    at async ESMLoader.import (node:internal/modules/esm/loader:527:24)                                                                                                                                       
    at async loadESM (node:internal/process/esm_loader:91:5)                                                                                                                                                  
    at async handleMainPromise (node:internal/modules/run_main:65:12) {                                                                                                                                       
  errno: -2,                                                                                                                                                                                                  
  syscall: 'open',                                                                                                                                                                                            
  code: 'ENOENT',                                                                                                                                                                                             
  path: './build-assets.json'                                                                                                                                                                                 
}                                                                                                                                                                                                             
                                                                                                                                                                                                              
Node.js v18.9.0  
```

**Comment by radokristof** [comment]
@BlackthornYugen any updates on this?

**Comment by BlackthornYugen** [comment]
@radokristof I haven't had any time to put towards this in a while. We started a PR here to update the official image: https://github.com/docker-library/official-images/pull/13162 but we found an issue and needed to publish a new version to fix it I think.
